/* Generated by fetch-book-details.mjs — do not edit by hand.
   Extra metadata for early books + discover-library books,
   overlaid onto book objects at render time by app.js. */
const BOOK_DETAILS = {
  "ouas-a-flicker-of-hope-a-story-of-migration": {
    "pages": 32,
    "isbn13": "9798855054347",
    "isbn10": "0593525760",
    "publisher": "Penguin Young Readers Group",
    "published": "2024",
    "source": "openlibrary"
  },
  "ouas-a-is-for-apple": {
    "isbn13": "9781589258723",
    "isbn10": "158925872X",
    "publisher": "Tiger Tales",
    "published": "2011",
    "source": "openlibrary"
  },
  "ouas-a-treasury-to-read-with-grandma": {
    "pages": 192,
    "isbn13": "9781680524659",
    "isbn10": "1680524658",
    "publisher": "Cottage Door Press",
    "published": "2018",
    "source": "openlibrary"
  },
  "ouas-ada-twist-scientist": {
    "pages": 32,
    "isbn13": "9781613129685",
    "isbn10": "1644730340",
    "publisher": "Dreamscape Media",
    "published": "2016",
    "synopsis": "Ada Twist, Scientist is a 2016 children's picture book written by Andrea Beaty and illustrated by David Roberts. The story was well received and praised for encouraging children, especially girls, to develop an interest in STEM.",
    "source": "openlibrary"
  },
  "ouas-blue-hat-green-hat": {
    "pages": 14,
    "isbn13": "9780671493202",
    "isbn10": "041649840X",
    "publisher": "Little Simon",
    "published": "1984",
    "synopsis": "Humorous animal characters introduce the basic colors and familiar items of clothing. On board pages.",
    "source": "openlibrary"
  },
  "ouas-brown-bear-brown-bear-what-do-you-see": {
    "pages": 28,
    "isbn13": "9780805017441",
    "isbn10": "4032015600",
    "publisher": "Picture Lions",
    "published": "1967",
    "synopsis": "Children see a variety of animals, each one a different color, and a teacher looking at them.",
    "source": "openlibrary"
  },
  "ouas-caillou-and-rosie-s-doll": {
    "pages": 24,
    "isbn13": "9782894501832",
    "isbn10": "2894501838",
    "publisher": "Chouette",
    "published": "2000",
    "source": "openlibrary"
  },
  "ouas-chicka-chicka-boom-boom": {
    "pages": 40,
    "isbn13": "9780671679491",
    "isbn10": "0590438891",
    "publisher": "Shang yi wen hua shi ye gu fen you xian gong si",
    "published": "1989",
    "synopsis": "An alphabet rhyme/chant that relates what happens when the whole alphabet tries to climb a coconut tree.",
    "source": "openlibrary"
  },
  "ouas-contemplating-your-bellybutton": {
    "isbn13": "9780916291600",
    "isbn10": "091629160X",
    "publisher": "Kane/Miller Book Publishers",
    "published": "1995",
    "source": "openlibrary"
  },
  "ouas-counting-on-community": {
    "isbn13": "9781609806323",
    "isbn10": "1609806328",
    "publisher": "Seven Stories Press",
    "published": "2015",
    "synopsis": "Counting up from one stuffed pinata to ten hefty hens--and always counting on each other--children are encouraged to recognize the value of their community, the joys inherent in healthy eco-friendly activities, and the agency they posses to make change.",
    "source": "openlibrary"
  },
  "ouas-cuentos-buenas-noches-ninas-rebeldes-1": {
    "pages": 224,
    "isbn13": "9786070749483",
    "isbn10": "6070749480",
    "publisher": "Planeta",
    "published": "2017",
    "source": "openlibrary"
  },
  "ouas-cuentos-buenas-noches-ninas-rebeldes-2": {
    "pages": 224,
    "isbn13": "9786070749483",
    "isbn10": "6070749480",
    "publisher": "Planeta",
    "published": "2017",
    "source": "openlibrary"
  },
  "ouas-dc-super-hero-girls-finals-crisis": {
    "pages": 128,
    "isbn13": "9781515888581",
    "isbn10": "151587432X",
    "publisher": "Capstone",
    "published": "2016",
    "source": "openlibrary"
  },
  "ouas-dinosaur-dance": {
    "pages": 16,
    "isbn13": "9781665907903",
    "isbn10": "1481480995",
    "publisher": "Little Simon",
    "published": "2016",
    "synopsis": "Join Boynton’s lively prehistoric bunch as they get everyone’s tails shaking for a feet-stomping good time. Whether they dance the Shimmy Shimmy Shake, the Quivery Quake, or just decide to Cha-Cha-Cha, young readers are sure to giggle along with these adorable creatures that are ready for a ROARING good time!",
    "source": "openlibrary"
  },
  "ouas-dinosnores": {
    "pages": 24,
    "isbn13": "9781523508136",
    "isbn10": "1523508132",
    "publisher": "Simon & Schuster Children's Publishing",
    "published": "2019",
    "source": "openlibrary"
  },
  "ouas-dora-s-big-book-of-stories": {
    "pages": 192,
    "isbn13": "9781416907084",
    "isbn10": "1416907084",
    "publisher": "Simon Spotlight/Nickelodeon",
    "published": "2005",
    "source": "openlibrary"
  },
  "ouas-dr-seuss-s-abc": {
    "pages": 64,
    "isbn13": "9780676733037",
    "isbn10": "0001711164",
    "publisher": "Random House BFYR",
    "published": "1960",
    "synopsis": "It is Dr. Seuss again with this handy books for parents to make their children learn the basic ABCs with this funny and whimsical mind of Dr. Seuss in this very colour-illustrated children book. Parents would love using this book to teach their children.",
    "source": "openlibrary"
  },
  "ouas-each-peach-pear-plum": {
    "pages": 32,
    "isbn13": "9780141502526",
    "isbn10": "0670058971",
    "publisher": "Penguin Books, Limited",
    "published": "1978",
    "synopsis": "Rhymed text and illustrations invite the reader to play \"I Spy\" with a variety of Mother Goose and other folklore characters",
    "source": "openlibrary"
  },
  "ouas-first-words-spanish": {
    "pages": 206,
    "isbn13": "9781786573179",
    "isbn10": "1786573172",
    "publisher": "Lonely Planet",
    "published": "2017",
    "synopsis": "Help young children unlock the Spanish language while travelling with First Words Spanish.",
    "source": "openlibrary"
  },
  "ouas-fish-upon-a-star": {
    "isbn13": "9781955044974",
    "isbn10": "195504497X",
    "publisher": "Little Hippo Books",
    "published": "2021",
    "source": "openlibrary"
  },
  "ouas-friendship-is-forever": {
    "pages": 22,
    "isbn13": "9780593377147",
    "isbn10": "1838913602",
    "publisher": "Little Tiger Press Group",
    "published": "2021",
    "source": "openlibrary"
  },
  "ouas-good-night-grand-canyon": {
    "pages": 20,
    "isbn13": "9781602195035",
    "isbn10": "160219503X",
    "publisher": "Good Night Books",
    "published": "2016",
    "source": "openlibrary"
  },
  "ouas-good-night-i-love-you": {
    "pages": 24,
    "isbn13": "9781444925609",
    "isbn10": "1444925601",
    "publisher": "Hachette Children's Group",
    "published": "2016",
    "source": "openlibrary"
  },
  "ouas-goodnight-moon": {
    "pages": 32,
    "isbn13": "9780616015988",
    "isbn10": "0749730072",
    "publisher": "Two Hoots",
    "published": "1947",
    "synopsis": "Goodnight to each of the objects in the great green room: the chairs, a comb, and the air.",
    "source": "openlibrary"
  },
  "ouas-happy-birthday-to-you": {
    "pages": 64,
    "isbn13": "9780394800769",
    "isbn10": "0785787941",
    "publisher": "HarperCollins Publishers Limited",
    "published": "1959",
    "synopsis": "Describes a birthday celebration in Katroo presided over by the Birthday Bird.",
    "source": "openlibrary"
  },
  "ouas-hippos-go-berserk": {
    "pages": 30,
    "isbn13": "9780316104944",
    "isbn10": "0689808186",
    "publisher": "Little Brown & Co",
    "published": "1979",
    "synopsis": "Larger and larger groups of hippos join a lone hippopotamus for a party.",
    "source": "openlibrary"
  },
  "ouas-how-to-tie-your-shoes": {
    "pages": 10,
    "isbn13": "9781680523188",
    "isbn10": "168052318X",
    "publisher": "Cottage Door Press",
    "published": "2018",
    "source": "openlibrary"
  },
  "ouas-hugs": {
    "pages": 30,
    "isbn13": "9781443142939",
    "isbn10": "1443142905",
    "publisher": "Scholastic Canada, Limited",
    "published": "2014",
    "synopsis": "Théa and her brother go for a walk around the block. They meet a snail, a skunk, a porcupine, and a gorilla, and get a hug from each one, but the hugs are slimy, smelly, pokey, and way too hard. It's not until they get back to their mother that they get a really good hug.",
    "source": "openlibrary"
  },
  "ouas-i-am-a-big-sister": {
    "pages": 24,
    "isbn13": "9780545688987",
    "isbn10": "0545688981",
    "publisher": "Cartwheel Books",
    "published": "2015",
    "source": "openlibrary"
  },
  "ouas-i-am-enough": {
    "pages": 32,
    "isbn13": "9798855019889",
    "isbn10": "0062667122",
    "publisher": "Scholastic",
    "published": "2018",
    "synopsis": "We are all here for a purpose. We are more than enough. We just need to believe it.",
    "source": "openlibrary"
  },
  "ouas-i-am-love": {
    "pages": 32,
    "isbn13": "9781419737268",
    "isbn10": "141974237X",
    "publisher": "Abrams, Inc.",
    "published": "2019",
    "source": "openlibrary"
  },
  "ouas-i-want-my-hat-back": {
    "pages": 40,
    "isbn13": "9780545571524",
    "isbn10": "0763696765",
    "publisher": "scholastic",
    "published": "2011",
    "synopsis": "The bear's hat is gone, and he wants it back. Patiently and politely, he asks the animals he comes across, one by one, whether they have seen it. Each animal says no, some more elaborately than others. But just as the bear begins to despair, a deer comes by and asks a simple question that sparks the bear's memory and renews his search with a vengeance. A picture-book morality play about dishonesty.",
    "source": "openlibrary"
  },
  "ouas-i-will-love-you-forever": {
    "pages": 22,
    "isbn13": "9780545942003",
    "isbn10": "0545942004",
    "publisher": "Scholastic, Incorporated",
    "published": "2017",
    "source": "openlibrary"
  },
  "ouas-in-my-heart-a-book-of-feelings": {
    "isbn13": "9781419713101",
    "isbn10": "1419713108",
    "publisher": "Abrams",
    "published": "2014",
    "synopsis": "A young girl explores what different emotions feel like, such as happiness which makes her want to twirl, or sadness which feels as heavy as an elephant.",
    "source": "openlibrary"
  },
  "ouas-is-your-mama-a-llama": {
    "pages": 32,
    "isbn13": "9780590259385",
    "isbn10": "0439875889",
    "publisher": "Scholastic Audio Books",
    "published": "1989",
    "synopsis": "Lloyd the llama is looking for his mama. \"Is your mama a llama?\" he asks a bat, a swan, a cow, a seal, and a kangaroo. Young children will share Lloyd's delight when the answer to his question is finally, \"Yes!\" With rhyme and riddle, this charming story has become a favorite. - Publisher.",
    "source": "openlibrary"
  },
  "ouas-it-s-my-body": {
    "isbn13": "9781443196505",
    "isbn10": "1443196509",
    "publisher": "Scholastic",
    "published": "2023",
    "source": "openlibrary"
  },
  "ouas-just-a-special-day": {
    "pages": 32,
    "isbn13": "9780061478178",
    "isbn10": "0061478172",
    "publisher": "HarperCollins Publishers",
    "published": "2014",
    "source": "openlibrary"
  },
  "ouas-just-go-to-bed": {
    "pages": 24,
    "isbn13": "9780808563969",
    "isbn10": "1552250547",
    "publisher": "Turtleback Books Distributed by Demco Media",
    "published": "1983",
    "synopsis": "A small rabbit uses his imagination to avoid going to bed, but finally has to admit that he is sleepy.",
    "source": "openlibrary"
  },
  "ouas-little-penguin-gets-the-hiccups": {
    "pages": 34,
    "isbn13": "9780062652249",
    "isbn10": "0062652249",
    "publisher": "Balzer + Bray",
    "published": "2016",
    "synopsis": "Poor Little Penguin has a major case of the—HIC!—hiccups. It all started last week, on chili night. Since then he’s tried everything to get rid of them, but nothing—HIC!—works. Can you help Little Penguin—HIC!—cure his hiccups?",
    "source": "openlibrary"
  },
  "ouas-llama-llama-red-pajama": {
    "pages": 34,
    "isbn13": "9780545030106",
    "isbn10": "0425290395",
    "publisher": "Viking",
    "published": "2005",
    "synopsis": "Baby Llama turns bedtime into an all-out llama drama! Tucked into bed by his mama, Baby Llama immediately starts worrying when she goes downstairs, and his soft whimpers turn to hollers when she doesn't come right back. But just in time, Mama returns to set things right. Children will relate to Baby Llama's need for comfort, as much as parents will appreciate Mama Llama's reassuring message.",
    "source": "openlibrary"
  },
  "ouas-llamas-go-bananas": {
    "isbn13": "9781787723160",
    "isbn10": "178772316X",
    "publisher": "Bookoli Limited",
    "published": "2019",
    "source": "openlibrary"
  },
  "ouas-love-you-head-to-toe": {
    "pages": 30,
    "isbn13": "9781771474030",
    "isbn10": "1771473045",
    "publisher": "Owlkids Books Inc.",
    "published": "2019",
    "source": "openlibrary"
  },
  "ouas-marisol-mcdonald-doesn-t-match": {
    "pages": 31,
    "isbn13": "9780892392353",
    "isbn10": "0892392355",
    "publisher": "Children's Book Press",
    "published": "2011",
    "synopsis": "Marisol McDonald, a biracial, nonconformist, soccer-playing pirate-princess with brown skin and red hair, celebrates her uniqueness.",
    "source": "openlibrary"
  },
  "ouas-mi-abuela-me-quiere-123": {
    "isbn13": "9781638540908",
    "isbn10": "163854090X",
    "publisher": "Kidsbooks, LLC",
    "published": "2022",
    "source": "openlibrary"
  },
  "ouas-mud-puddle": {
    "pages": 32,
    "isbn13": "9781773216584",
    "isbn10": "0920236472",
    "publisher": "Distributed in Canada and the U.S.A. by Firefly Books",
    "published": "1979",
    "synopsis": "When Jule Ann goes outside, a mud puddle jumps on her and gets her dirty all over. No sooner does her mother scrub her clean than she ventures out again, only to be pounced upon by the pesky mud puddle. The cycle continues until finally Jule Ann gets the better of the mud puddle with cheerful ingenuity and two bars of smelly yellow soap.",
    "source": "openlibrary"
  },
  "ouas-narwhalicorn-and-jelly": {
    "pages": 80,
    "isbn13": "9780735266728",
    "isbn10": "0735266840",
    "publisher": "Tundra",
    "published": "2022",
    "source": "openlibrary"
  },
  "ouas-neither": {
    "pages": 26,
    "isbn13": "9780316411479",
    "isbn10": "0316411469",
    "publisher": "LB Kids",
    "published": "2018",
    "synopsis": "In the Land of This and That, there are only two kinds: blue bunnies and yellow birds. But one day a funny green egg hatches, and a little creature that's not quite a bird and not quite a bunny pops out. It's neither! Neither tries hard to fit in, but its bird legs aren't good for jumping like the other bunnies, and its fluffy tail isn't good for flapping like the other birds.",
    "source": "openlibrary"
  },
  "ouas-oh-the-thinks-you-can-think": {
    "pages": 41,
    "isbn13": "9780394931296",
    "isbn10": "0394883314",
    "publisher": "Random House",
    "published": "1975",
    "source": "openlibrary"
  },
  "ouas-one-eagle-soaring": {
    "pages": 20,
    "isbn13": "9781550178289",
    "isbn10": "1550178288",
    "publisher": "Harbour Publishing Company, Limited",
    "published": "2018",
    "source": "openlibrary"
  },
  "ouas-opposites": {
    "pages": 16,
    "isbn13": "9780416455106",
    "isbn10": "0689835000",
    "publisher": "Methuen Publishing Ltd",
    "published": "1982",
    "synopsis": "Book of opposite words.",
    "source": "openlibrary"
  },
  "ouas-panorama-pops-rome": {
    "pages": 15,
    "isbn13": "9780763664152",
    "isbn10": "0763664154",
    "publisher": "Candlewick",
    "published": "2013",
    "source": "openlibrary"
  },
  "ouas-peek-a-boo-haiku": {
    "isbn13": "9781665926461",
    "isbn10": "1665926465",
    "publisher": "Little Simon",
    "published": "2023",
    "source": "openlibrary"
  },
  "ouas-penguin-in-love": {
    "pages": 35,
    "isbn13": "9780802736017",
    "isbn10": "0802736009",
    "publisher": "Scholastic Inc., by arrangement with Walker Books for Young Readers, an imprint of Bloomsbury Publishng, Inc.",
    "published": "2013",
    "synopsis": "**Geisel Honor-winning author/illustrator Salina Yoon's beloved character Penguin** searches for his match in **Penguin in Love** - a charming picture book that's perfect for Valentine's Day. When Penguin finds a lost mitten on the ice one day, he wonders who it belongs to - after all, every mitten has a mate! To unravel the mystery, he embarks on the biggest adventure of his life. **Is love waiting for Penguin at the end of this incredible journey?**",
    "source": "openlibrary"
  },
  "ouas-pigs": {
    "pages": 32,
    "isbn13": "9781773216539",
    "isbn10": "1550371916",
    "publisher": "Demco Media",
    "published": "1989",
    "synopsis": "Recounts Megan's adventures when she opens the gate to the pig pen while feeding the pigs, although she had been warned not to do so",
    "source": "openlibrary"
  },
  "ouas-princess-truly-i-am-curious": {
    "pages": 48,
    "isbn13": "9781338818857",
    "isbn10": "1338818864",
    "publisher": "Scholastic, Incorporated",
    "published": "2023",
    "source": "openlibrary"
  },
  "ouas-the-bunny-rabbit-show": {
    "isbn13": "9780761180609",
    "isbn10": "0761180605",
    "published": "2014",
    "synopsis": "Introduces ten rabbits who like to dance, sing, jump, and wiggle their noses in unison to entertain their audience, but anyone is welcome to join the chorus line after donning a pair of bunny ears.",
    "source": "openlibrary"
  },
  "ouas-the-family-book": {
    "pages": 32,
    "isbn13": "9780316155632",
    "isbn10": "9577623689",
    "publisher": "Little, Brown Books for Young Readers",
    "published": "2003",
    "synopsis": "Represents a variety of families, some big and some small, some with only one parent and some with two moms or dads, some quiet and some noisy, but all alike in some ways and special no matter what.",
    "source": "openlibrary"
  },
  "ouas-the-going-to-bed-book": {
    "pages": 14,
    "isbn13": "9780689861147",
    "isbn10": "1442454091",
    "publisher": "Simon & Schuster Books For Young Readers",
    "published": "1982",
    "synopsis": "An assortment of animals on a boat take a bath, put on their pajamas, brush their teeth, and exercise before going to bed.",
    "source": "openlibrary"
  },
  "ouas-the-greedy-python": {
    "pages": 24,
    "isbn13": "9780689820595",
    "isbn10": "0590622331",
    "publisher": "Scholastic, Inc.",
    "published": "1993",
    "source": "openlibrary"
  },
  "ouas-the-paper-bag-princess": {
    "pages": 32,
    "isbn13": "9780439977821",
    "isbn10": "3473446386",
    "publisher": "Bradan Press",
    "published": "1980",
    "synopsis": "Story about not accepting failure or giving up on what you want. It's not about looks or power but tenacity and quick thinking. Hurray for you Princess of the Paper Bag. Very short, easy reading. I wanted to hear more about her.",
    "source": "openlibrary"
  },
  "ouas-the-sunken-ship-an-acorn-book-mermaid-days-1": {
    "pages": 60,
    "isbn13": "9781338794595",
    "isbn10": "1338794590",
    "publisher": "Bound to Stay Bound Books",
    "published": "2022",
    "source": "openlibrary"
  },
  "ouas-the-very-hungry-caterpillar": {
    "pages": 26,
    "isbn13": "9788416126835",
    "isbn10": "2871421749",
    "publisher": "Penguin Books, Limited",
    "published": "1969",
    "synopsis": "One sunny day, a caterpillar pops out of an egg. He is very hungry and begins searching for food. He eats his way through ten very sweet pages and gets a tummy ache before finally finding a good, healthy leaf, which makes him sleepy. Then something really amazing happens. But you will have to read it your self to find out what!",
    "source": "openlibrary"
  },
  "ouas-the-wonky-donkey": {
    "pages": 24,
    "isbn13": "9781407195414",
    "isbn10": "1407198521",
    "publisher": "Scholastic",
    "published": "2010",
    "synopsis": "While walking down the road, the narrator sees a donkey that he shares more about as the story progresses.",
    "source": "openlibrary"
  },
  "ouas-time-for-bed": {
    "pages": 30,
    "isbn13": "9780152881832",
    "isbn10": "1874371504",
    "publisher": "Hazar",
    "published": "1993",
    "synopsis": "Darkness is falling and everywhere little ones are growing sleepy and being tucked into bed. Sleep tight!",
    "source": "openlibrary"
  },
  "ouas-treasury-of-fairy-tales": {
    "pages": 383,
    "isbn13": "9780785307013",
    "isbn10": "078530701X",
    "publisher": "Phoenix Intl Pubns Inc",
    "published": "1994",
    "source": "openlibrary"
  },
  "ouas-twinkle-makes-music": {
    "pages": 32,
    "isbn13": "9781534496767",
    "isbn10": "1536475890",
    "publisher": "Simon Spotlight",
    "published": "2022",
    "source": "openlibrary"
  },
  "ouas-un-amigo-como-tu-ardilla-y-sus-amigos": {
    "isbn13": "9788448847272",
    "isbn10": "844884727X",
    "publisher": "Beascoa",
    "published": "2017",
    "source": "openlibrary"
  },
  "ouas-we-re-different-we-re-the-same": {
    "pages": 40,
    "isbn13": "9781524770563",
    "isbn10": "1524770566",
    "publisher": "Random House Books for Young Readers",
    "published": "2017",
    "source": "openlibrary"
  },
  "ouas-what-s-wrong-little-pookie": {
    "pages": 18,
    "isbn13": "9780375845529",
    "isbn10": "1481497693",
    "publisher": "Little Simon",
    "published": "2007",
    "synopsis": "When Pookie feels down, Pookie s mom can always guess what s wrong with her little one. Or can she?",
    "source": "openlibrary"
  },
  "ouas-when-we-are-kind": {
    "pages": 32,
    "isbn13": "9781459821460",
    "isbn10": "1459821467",
    "publisher": "Orca Book Publishers USA",
    "published": "2020",
    "source": "openlibrary"
  },
  "ouas-why-i-love-my-abc": {
    "isbn13": "9780008519223",
    "isbn10": "0008519218",
    "publisher": "HarperCollins Publishers Limited",
    "published": "2022",
    "source": "openlibrary"
  },
  "ouas-winnie-the-pooh-senses": {
    "pages": 20,
    "isbn13": "9780736410090",
    "isbn10": "0736410090",
    "publisher": "RH/Disney",
    "published": "1999",
    "synopsis": "When Pooh uses his five senses, he finds a sweet surprise!",
    "source": "openlibrary"
  },
  "ouas-you-re-my-little-baby": {
    "pages": 23,
    "isbn13": "9783806746280",
    "isbn10": "3806746281",
    "publisher": "Gerstenberg, Hildesh.",
    "published": "1991",
    "source": "openlibrary"
  },
  "ouas-your-personal-penguin": {
    "pages": 24,
    "isbn13": "9780761143727",
    "isbn10": "0761143726",
    "publisher": "Workman Publishing Company",
    "published": "2006",
    "source": "openlibrary"
  },
  "boris-1": {
    "isbn13": "9780545484435",
    "isbn10": "054548443X",
    "publisher": "Scholastic",
    "published": "2014",
    "source": "openlibrary"
  },
  "boris-2": {
    "isbn13": "9780545484473",
    "isbn10": "0545484472",
    "publisher": "Scholastic",
    "published": "2013",
    "source": "openlibrary"
  },
  "boris-3": {
    "isbn13": "9780545484497",
    "isbn10": "0545484499",
    "publisher": "Scholastic",
    "published": "2013",
    "source": "openlibrary"
  },
  "boris-4": {
    "pages": 80,
    "isbn13": "9780545484534",
    "isbn10": "0545484537",
    "publisher": "Scholastic Inc.",
    "published": "2013",
    "source": "openlibrary"
  },
  "diary-of-a-dinoghost-1": {
    "pages": 96,
    "isbn13": "9798295205415",
    "publisher": "Scholastic, Incorporated",
    "published": "2026",
    "source": "openlibrary"
  },
  "diary-of-a-pug-1": {
    "pages": 80,
    "isbn13": "9781338845839",
    "isbn10": "1338845837",
    "publisher": "Scholastic Inc.",
    "published": "2022",
    "source": "openlibrary"
  },
  "diary-of-a-pug-2": {
    "isbn13": "9781338530070",
    "isbn10": "1338530070",
    "publisher": "Scholastic Inc.",
    "published": "2020",
    "source": "openlibrary"
  },
  "diary-of-a-pug-3": {
    "pages": 80,
    "isbn13": "9781338530117",
    "isbn10": "1338530097",
    "publisher": "Scholastic, Incorporated",
    "published": "2020",
    "source": "openlibrary"
  },
  "diary-of-a-pug-4": {
    "pages": 80,
    "isbn13": "9781338530124",
    "isbn10": "1338530127",
    "publisher": "Scholastic, Incorporated",
    "published": "2020",
    "source": "openlibrary"
  },
  "diary-of-a-pug-5": {
    "pages": 80,
    "isbn13": "9781338713459",
    "isbn10": "1338713450",
    "publisher": "Scholastic Press",
    "published": "2021",
    "source": "openlibrary"
  },
  "diary-of-a-pug-6": {
    "pages": 80,
    "isbn13": "9781338713473",
    "isbn10": "1338713477",
    "publisher": "Scholastic, Incorporated",
    "published": "2022",
    "source": "openlibrary"
  },
  "diary-of-a-pug-7": {
    "pages": 80,
    "isbn13": "9781338713503",
    "isbn10": "1536476161",
    "publisher": "Scholastic Inc.",
    "published": "2022",
    "source": "openlibrary"
  },
  "diary-of-a-pug-8": {
    "isbn13": "9781338713534",
    "isbn10": "1338713531",
    "publisher": "Scholastic, Incorporated",
    "published": "2023",
    "source": "openlibrary"
  },
  "diary-of-a-pug-9": {
    "isbn13": "9781338877571",
    "isbn10": "1338877577",
    "publisher": "Scholastic, Incorporated",
    "published": "2023",
    "source": "openlibrary"
  },
  "diary-of-a-pug-10": {
    "isbn13": "9781338877601",
    "isbn10": "1338877615",
    "publisher": "Scholastic, Incorporated",
    "published": "2024",
    "source": "openlibrary"
  },
  "diary-of-a-pug-11": {
    "pages": 80,
    "isbn13": "9781536488548",
    "isbn10": "1536488542",
    "publisher": "Scholastic, Incorporated",
    "published": "2024",
    "source": "openlibrary"
  },
  "diary-of-a-pug-12": {
    "pages": 80,
    "isbn13": "9781338877663",
    "isbn10": "1338877666",
    "publisher": "Scholastic, Incorporated",
    "published": "2025",
    "source": "openlibrary"
  },
  "diary-of-a-pug-13": {
    "pages": 80,
    "isbn13": "9781546139195",
    "isbn10": "1546139192",
    "publisher": "Scholastic, Incorporated",
    "published": "2025",
    "source": "openlibrary"
  },
  "diary-of-a-pug-14": {
    "pages": 80,
    "isbn13": "9781546139225",
    "isbn10": "1546139222",
    "publisher": "Scholastic, Incorporated",
    "published": "2025",
    "source": "openlibrary"
  },
  "disaster-squad-1": {
    "pages": 96,
    "isbn13": "9781536487848",
    "isbn10": "1536487848",
    "publisher": "Scholastic, Incorporated",
    "published": "2024",
    "source": "openlibrary"
  },
  "disaster-squad-2": {
    "pages": 96,
    "isbn13": "9781338828870",
    "isbn10": "1338828878",
    "publisher": "Scholastic, Incorporated",
    "published": "2024",
    "source": "openlibrary"
  },
  "disaster-squad-3": {
    "pages": 96,
    "isbn13": "9781536489651",
    "isbn10": "1338828894",
    "publisher": "Scholastic, Incorporated",
    "published": "2024",
    "source": "openlibrary"
  },
  "disaster-squad-4": {
    "pages": 96,
    "isbn13": "9781338828931",
    "isbn10": "1338828932",
    "publisher": "Scholastic",
    "published": "2025",
    "source": "openlibrary"
  },
  "eerie-elementary-1": {
    "pages": 92,
    "isbn13": "9781532142604",
    "isbn10": "1532142609",
    "publisher": "Chapter Books",
    "published": "2018",
    "source": "openlibrary"
  },
  "eerie-elementary-2": {
    "isbn13": "9781532142611",
    "isbn10": "0606360522",
    "publisher": "Chapter Books",
    "published": "2014",
    "source": "openlibrary"
  },
  "eerie-elementary-3": {
    "isbn13": "9780545873529",
    "isbn10": "1532142625",
    "publisher": "Scholastic",
    "published": "2016",
    "source": "openlibrary"
  },
  "eerie-elementary-4": {
    "pages": 92,
    "isbn13": "9781532142635",
    "isbn10": "1532142633",
    "publisher": "Chapter Books",
    "published": "2018",
    "source": "openlibrary"
  },
  "eerie-elementary-5": {
    "pages": 90,
    "isbn13": "9780545873734",
    "isbn10": "0545873738",
    "publisher": "Spotlight",
    "published": "2016",
    "synopsis": "A heavy snowstorm traps the students inside Eerie Elementary, a living, breathing monster brought to life by mad scientist, Orson Eerie--soon the school begins to freeze from the inside out, and Sam, Lucy and Antonio must find a way to get the heat back on before all the students freeze to death, while facing the truth that Orson Eerie is even more powerful and dangerous than they realized.",
    "source": "openlibrary"
  },
  "eerie-elementary-6": {
    "pages": 96,
    "isbn13": "9780545873796",
    "isbn10": "0545873797",
    "publisher": "Scholastic Inc.",
    "published": "2017",
    "source": "openlibrary"
  },
  "eerie-elementary-7": {
    "pages": 96,
    "isbn13": "9780606406697",
    "isbn10": "0606406697",
    "publisher": "Turtleback Books",
    "published": "2017",
    "source": "openlibrary"
  },
  "eerie-elementary-8": {
    "pages": 96,
    "isbn13": "9780606415491",
    "isbn10": "153643907X",
    "publisher": "Scholastic, Incorporated",
    "published": "2018",
    "source": "openlibrary"
  },
  "eerie-elementary-9": {
    "pages": 96,
    "isbn13": "9780606415507",
    "isbn10": "0606415505",
    "publisher": "Turtleback Books",
    "published": "2018",
    "source": "openlibrary"
  },
  "eerie-elementary-10": {
    "pages": 96,
    "isbn13": "9781338318562",
    "isbn10": "133831856X",
    "publisher": "Branches",
    "published": "2019",
    "source": "openlibrary"
  },
  "geronimo-stilton-1": {
    "isbn13": "9780307206916",
    "isbn10": "1400091209",
    "publisher": "Imagination Studio",
    "published": "2004",
    "source": "openlibrary"
  },
  "geronimo-stilton-2": {
    "isbn13": "9780307206916",
    "isbn10": "1400091209",
    "publisher": "Imagination Studio",
    "published": "2004",
    "source": "openlibrary"
  },
  "geronimo-stilton-7": {
    "isbn13": "9780307245212",
    "isbn10": "0307245209",
    "publisher": "Imagination Studio",
    "published": "2005",
    "source": "openlibrary"
  },
  "geronimo-stilton-8": {
    "isbn13": "9780307245212",
    "isbn10": "0307245209",
    "publisher": "Imagination Studio",
    "published": "2005",
    "source": "openlibrary"
  },
  "geronimo-stilton-11": {
    "pages": 128,
    "isbn13": "9788408067863",
    "isbn10": "0545391857",
    "publisher": "Xin ya wen hua shi ye you xian gong si",
    "published": "1995",
    "synopsis": "Crumbling cheese treats! It was Halloween, the spookiest day of the year, and my nephew Benjamin had dragged me to a graveyard to do research for my newest book. There I met Creepella von Cacklefur, a very spooky mouse who- yikes!- tried to lock me up in her coffin! Oh, how would a 'fraidy mouse like me ever survive?",
    "source": "openlibrary"
  },
  "geronimo-stilton-17": {
    "pages": 128,
    "isbn13": "9781415582053",
    "isbn10": "141558205X",
    "publisher": "Xin ya wen hua shi ye you xian gong si",
    "published": "2000",
    "synopsis": "This one-eyed rat is running around town buying out Geronimo's newspapers, books, and even his office. Geronimo calls Shif T. Paws to come and help him out. Shif has alot of great ideas but Geronimo doesn't like them them that much. He wins a million dollars when he plays The Mousetrap and saves his newspaper. Geronimo figures out who the one-eyed rat is but no other than.....",
    "source": "openlibrary"
  },
  "geronimo-stilton-18": {
    "pages": 128,
    "isbn13": "9781536432763",
    "isbn10": "9620840976",
    "publisher": "Xin ya wen hua shi ye you xian gong si",
    "published": "2005",
    "synopsis": "Really good cos it is. 😎",
    "source": "openlibrary"
  },
  "geronimo-stilton-20": {
    "pages": 2,
    "isbn13": "9780545203098",
    "isbn10": "0545203090",
    "publisher": "Scholastic Audio Books",
    "published": "2010",
    "source": "openlibrary"
  },
  "geronimo-stilton-21": {
    "pages": 2,
    "isbn13": "9780545203098",
    "isbn10": "0545203090",
    "publisher": "Scholastic Audio Books",
    "published": "2010",
    "source": "openlibrary"
  },
  "geronimo-stilton-23": {
    "pages": 113,
    "isbn13": "9780606347679",
    "isbn10": "0606347674",
    "publisher": "Scholastic",
    "published": "2006",
    "synopsis": "Enter the world of Geronimo Stilton, where another funny adventure is always right around the corner. Each book is a fast-paced adventure with lively art and a unique format kids 7-10 will love.It was Valentine's Day in New Mouse City, and I couldn't wait to celebrate! I had sent valentine cards to all my friends and family members. But when I opened my mailbox on the morning of February 14th, it was empty! Had everyone forgotten about me?",
    "source": "openlibrary"
  },
  "geronimo-stilton-24": {
    "pages": 128,
    "isbn13": "9788408152538",
    "isbn10": "2226209433",
    "publisher": "Xin ya wen hua shi ye you xian gong si",
    "published": "2006",
    "synopsis": "When you're with Geronimo Stilton, it's always a fabumouse adventure! Holey cheese, what an adventure! I was off to Niagara Falls with my nephew Benjamin's class. It was a beautiful place -- truly one of the most amazing sights I'd ever seen. But unfortunately, I was surrounded by mischievous young mouselets who were determined to send me over the Falls in a barrel! Oh, would I ever make it back to Mouse Island alive?",
    "source": "openlibrary"
  },
  "geronimo-stilton-28": {
    "pages": 115,
    "isbn13": "9788838455292",
    "isbn10": "1782269452",
    "publisher": "Piemme",
    "published": "2000",
    "source": "openlibrary"
  },
  "geronimo-stilton-29": {
    "pages": 111,
    "isbn13": "9788838455698",
    "isbn10": "0439841208",
    "publisher": "21th Century Publishing House",
    "published": "2006",
    "synopsis": "Hilarious, Whisker- licking good.",
    "source": "openlibrary"
  },
  "geronimo-stilton-32": {
    "isbn13": "9781782267980",
    "isbn10": "1782267980",
    "publisher": "Sweet cherry publishing limited ",
    "published": "2021",
    "source": "openlibrary"
  },
  "geronimo-stilton-36": {
    "pages": 128,
    "isbn13": "9781782269465",
    "isbn10": "9085921007",
    "publisher": "Scholastic",
    "published": "2008",
    "synopsis": "When Geronimo gets a call to help Hercule Poirat solve a mystery at the same time as his date with Petunia Pretty Paws, what is a gentlemouse to do?",
    "source": "openlibrary"
  },
  "geronimo-stilton-46": {
    "pages": 123,
    "isbn13": "9781536423327",
    "isbn10": "0545393612",
    "publisher": "Elissabeta Dami",
    "published": "2007",
    "synopsis": "Geronimo Stilton (ik-figuur) wordt samen met zijn hele familie uitgenodigd door oom Adelmuis, om naar kasteel Vrekkenstein te komen. Wat zou er aan de hand zijn? Voorlezen vanaf ca. 7 jaar, zelf lezen vanaf ca. 9 jaar.",
    "source": "openlibrary"
  },
  "geronimo-stilton-48": {
    "isbn13": "9780329906177",
    "isbn10": "0329906178",
    "publisher": "Scholastic",
    "published": "2012",
    "source": "openlibrary"
  },
  "geronimo-stilton-53": {
    "isbn13": "9780606315272",
    "isbn10": "0606315276",
    "publisher": "Turtleback",
    "published": "2013",
    "source": "openlibrary"
  },
  "geronimo-stilton-62": {
    "isbn13": "9780545872515",
    "isbn10": "0545872510",
    "source": "openlibrary"
  },
  "geronimo-stilton-67": {
    "isbn13": "9789352751204",
    "isbn10": "9352751205",
    "published": "2017",
    "source": "openlibrary"
  },
  "geronimo-stilton-80": {
    "pages": 112,
    "isbn13": "9781802633122",
    "isbn10": "180263312X",
    "publisher": "Bound to Stay Bound Books",
    "published": "2022",
    "source": "openlibrary"
  },
  "geronimo-stilton-83": {
    "pages": 109,
    "isbn13": "9789354719820",
    "isbn10": "9354719821",
    "publisher": "Scholastic",
    "published": "2024",
    "source": "openlibrary"
  },
  "geronimo-stilton-84": {
    "pages": 128,
    "isbn13": "9781546141853",
    "isbn10": "1546141855",
    "publisher": "Scholastic Paperbacks",
    "published": "2025",
    "source": "openlibrary"
  },
  "geronimo-stilton-graphic-novels-18": {
    "pages": 53,
    "isbn13": "9781629916033",
    "isbn10": "162991603X",
    "publisher": "Mad Cave Studios",
    "published": "2016",
    "synopsis": "Geronimo and his friends go back in time and race the Pirate Cats to be the first to the South Pole.",
    "source": "openlibrary"
  },
  "geronimo-stilton-graphic-novels-19": {
    "pages": 55,
    "isbn13": "9781629917573",
    "isbn10": "1545800316",
    "publisher": "Mad Cave Studios",
    "published": "2017",
    "synopsis": "Geronimo and his friends go back in time to find the original Rosetta Stone, which the Pirate Cats have stolen and replaced with their own version.",
    "source": "openlibrary"
  },
  "geronimo-stilton-kingdom-of-fantasy-2": {
    "pages": 319,
    "isbn13": "9781338252774",
    "isbn10": "1338252771",
    "publisher": "Bound to Stay Bound Books",
    "published": "2006",
    "synopsis": "Invited by the Queen of the Fairies to return to her kingdom and help in the quest for the true heart of happiness, Geronimo soon finds himself on an adventurous journey riding on the wings of a rainbow-colored dragon through seven fantastic lands.",
    "source": "openlibrary"
  },
  "geronimo-stilton-kingdom-of-fantasy-10": {
    "pages": 448,
    "isbn13": "9788491373339",
    "isbn10": "8491373330",
    "publisher": "Destino Infantil & Juvenil",
    "published": "2016",
    "synopsis": "good",
    "source": "openlibrary"
  },
  "geronimo-stilton-kingdom-of-fantasy-11": {
    "pages": 318,
    "isbn13": "9781338215038",
    "isbn10": "1338215035",
    "publisher": "Scholastic",
    "published": "2018",
    "synopsis": "Geronimo is in the Kingdom of Fantasy for training on the \"Balanced Path\" when he learns that Queen Blossom has had a beautiful baby girl, Winglet, and that the baby princess has been kidnapped--and it is up to the brave mouse as Guardian of the Realm to discover who has taken Winglet, and return her to her distraught parents.",
    "source": "openlibrary"
  },
  "geronimo-stilton-kingdom-of-fantasy-15": {
    "pages": 512,
    "isbn13": "9798855130690",
    "isbn10": "1338848003",
    "publisher": "Destino Infantil & Juvenil",
    "published": "2018",
    "source": "openlibrary"
  },
  "haggis-and-tank-unleashed-1": {
    "pages": 80,
    "isbn13": "9780606381178",
    "isbn10": "0606381171",
    "publisher": "Scholastic, Incorporated",
    "published": "2015",
    "source": "openlibrary"
  },
  "haggis-and-tank-unleashed-2": {
    "isbn13": "9780545819718",
    "isbn10": "0545819717",
    "publisher": "Scholastic, Incorporated",
    "published": "2016",
    "source": "openlibrary"
  },
  "haggis-and-tank-unleashed-3": {
    "pages": 80,
    "isbn13": "9781338045253",
    "isbn10": "0606401903",
    "publisher": "Scholastic, Incorporated",
    "published": "2017",
    "source": "openlibrary"
  },
  "hilde-cracks-the-case-1": {
    "isbn13": "9781092601771",
    "isbn10": "1092601775",
    "publisher": "Independently Published",
    "published": "2019",
    "source": "openlibrary"
  },
  "kung-pow-chicken-1": {
    "pages": 72,
    "isbn13": "9798855084207",
    "publisher": "Bound to Stay Bound Books",
    "published": "2014",
    "source": "openlibrary"
  },
  "kung-pow-chicken-2": {
    "pages": 72,
    "isbn13": "9798855084160",
    "isbn10": "0606353577",
    "publisher": "Turtleback",
    "published": "2014",
    "source": "openlibrary"
  },
  "kung-pow-chicken-3": {
    "pages": 75,
    "isbn13": "9780606353588",
    "isbn10": "0606353585",
    "publisher": "Bound to Stay Bound Books",
    "published": "2014",
    "source": "openlibrary"
  },
  "kung-pow-chicken-5": {
    "pages": 72,
    "isbn13": "9798855084191",
    "publisher": "Bound to Stay Bound Books",
    "published": "2020",
    "source": "openlibrary"
  },
  "layla-and-the-bots-1": {
    "pages": 80,
    "isbn13": "9781338582895",
    "isbn10": "1536462683",
    "publisher": "Scholastic, Incorporated",
    "published": "2020",
    "source": "openlibrary"
  },
  "layla-and-the-bots-2": {
    "pages": 80,
    "isbn13": "9781338582949",
    "isbn10": "133858295X",
    "publisher": "Scholastic, Incorporated",
    "published": "2020",
    "source": "openlibrary"
  },
  "layla-and-the-bots-3": {
    "pages": 80,
    "isbn13": "9781338582994",
    "isbn10": "1338582984",
    "publisher": "Scholastic, Incorporated",
    "published": "2021",
    "source": "openlibrary"
  },
  "layla-and-the-bots-4": {
    "pages": 80,
    "isbn13": "9781338583014",
    "isbn10": "1338583018",
    "publisher": "Scholastic, Incorporated",
    "published": "2022",
    "source": "openlibrary"
  },
  "owl-diaries-1": {
    "pages": 80,
    "isbn13": "9781443153393",
    "isbn10": "1443153397",
    "publisher": "Scholastic Canada, Limited",
    "published": "2015",
    "synopsis": "Having a Bloomtastic Festival at school to celebrate spring is a great idea--but Eva Wingdale, a young owl, discovers that it is also a lot of work, and there is nothing wrong with asking her friends for help.",
    "source": "openlibrary"
  },
  "owl-diaries-2": {
    "pages": 80,
    "isbn13": "9780606370387",
    "isbn10": "0545787831",
    "publisher": "Scholastic",
    "published": "2015",
    "synopsis": "When Eva Wingdale sees something large and white flying above her she is convinced that it is a ghost, although most of the other owls just laugh at her--until something large and heavy and white lands on the school roof. \"¡Eva ve un fantasma! O al menos, eso piensa& Así que con su mejor amiga, sale en busca del fantasma. Perfecto para niñas a las que les encantan las historias de animales y de amistad. \"",
    "source": "openlibrary"
  },
  "owl-diaries-3": {
    "publisher": "Scholastic,Inc.",
    "published": "2016",
    "source": "openlibrary"
  },
  "owl-diaries-4": {
    "pages": 80,
    "isbn13": "9781338233469",
    "isbn10": "1338187929",
    "publisher": "Scholastic",
    "published": "2016",
    "synopsis": "A new owl named Hailey starts in Eva's class at school. Eva is always happy to meet new people, and she's excited to make a new friend! But the new owl befriends Lucy instead of her. So Eva gets jealous. Lucy is Eva's best friend! Will Eva lose her best friend? Or can Eva and Lucy BOTH make a new friend?",
    "source": "openlibrary"
  },
  "owl-diaries-5": {
    "isbn13": "9781098252274",
    "isbn10": "1098252276",
    "publisher": "Spotlight",
    "published": "2022",
    "source": "openlibrary"
  },
  "owl-diaries-6": {
    "pages": 80,
    "isbn13": "9781443165303",
    "isbn10": "133804284X",
    "publisher": "Scholastic, Incorporated",
    "published": "2017",
    "synopsis": "72 pages : 20 cm",
    "source": "openlibrary"
  },
  "owl-diaries-7": {
    "pages": 76,
    "isbn13": "9780876174951",
    "isbn10": "1424270790",
    "publisher": "Branches/Scholastic Inc.",
    "published": "2017",
    "synopsis": "Macy's little sister has wings that are too small, so Eva's class decides to raise money to buy her a flying chair, and half the class opens a bakery, and the other half opens a candy store--but soon competition between the two stores becomes more important than their goal, and Eva needs to convince the other owls that they will collect more money if everyone works as a team.",
    "source": "openlibrary"
  },
  "owl-diaries-8": {
    "isbn13": "9781098252304",
    "isbn10": "1098252306",
    "publisher": "Spotlight",
    "published": "2022",
    "source": "openlibrary"
  },
  "owl-diaries-9": {
    "isbn13": "9781338163087",
    "isbn10": "1338163086",
    "publisher": "Scholastic, Incorporated",
    "published": "2018",
    "source": "openlibrary"
  },
  "owl-diaries-10": {
    "isbn13": "9781098252328",
    "isbn10": "1098252322",
    "publisher": "Scholastic, Incorporated",
    "published": "2019",
    "source": "openlibrary"
  },
  "owl-diaries-11": {
    "pages": 76,
    "isbn13": "9781338298642",
    "isbn10": "133829864X",
    "publisher": "Branches",
    "published": "2019",
    "source": "openlibrary"
  },
  "owl-diaries-12": {
    "pages": 80,
    "isbn13": "9781338298697",
    "isbn10": "1338298690",
    "publisher": "Scholastic Inc.",
    "published": "2019",
    "source": "openlibrary"
  },
  "owl-diaries-13": {
    "pages": 80,
    "isbn13": "9781338298789",
    "isbn10": "1338298763",
    "publisher": "Penworthy Company, LLC, The",
    "published": "2020",
    "source": "openlibrary"
  },
  "owl-diaries-14": {
    "pages": 80,
    "isbn13": "9781338298819",
    "isbn10": "1338298828",
    "publisher": "Scholastic, Incorporated",
    "published": "2021",
    "source": "openlibrary"
  },
  "owl-diaries-15": {
    "isbn13": "9781536470659",
    "isbn10": "1536470651",
    "publisher": "Scholastic, Incorporated",
    "published": "2021",
    "source": "openlibrary"
  },
  "owl-diaries-16": {
    "pages": 80,
    "isbn13": "9781338745412",
    "isbn10": "1338745417",
    "publisher": "Scholastic",
    "published": "2022",
    "source": "openlibrary"
  },
  "owl-diaries-17": {
    "isbn13": "9781338745443",
    "isbn10": "1338745441",
    "publisher": "Scholastic, Incorporated",
    "published": "2022",
    "source": "openlibrary"
  },
  "owl-diaries-18": {
    "isbn13": "9781637994863",
    "isbn10": "1637994869",
    "publisher": "mukawa",
    "published": "2024",
    "source": "openlibrary"
  },
  "owl-diaries-19": {
    "isbn13": "9781536482683",
    "isbn10": "1338880276",
    "publisher": "Scholastic, Incorporated",
    "published": "2023",
    "source": "openlibrary"
  },
  "owl-diaries-20": {
    "isbn13": "9781637994863",
    "isbn10": "1637994869",
    "publisher": "mukawa",
    "published": "2024",
    "source": "openlibrary"
  },
  "owl-diaries-21": {
    "pages": 80,
    "isbn13": "9781546127079",
    "isbn10": "1546127070",
    "publisher": "Scholastic, Incorporated",
    "published": "2025",
    "source": "openlibrary"
  },
  "owl-diaries-22": {
    "pages": 80,
    "isbn13": "9781546127109",
    "isbn10": "1546127100",
    "publisher": "Scholastic, Incorporated",
    "published": "2025",
    "source": "openlibrary"
  },
  "pets-rule-5": {
    "isbn13": "9781339021584",
    "isbn10": "1339021587",
    "publisher": "Scholastic, Incorporated",
    "published": "2024",
    "source": "openlibrary"
  },
  "pets-rule-7": {
    "pages": 96,
    "isbn13": "9781546119760",
    "isbn10": "1546119760",
    "publisher": "Scholastic Inc.",
    "published": "2025",
    "source": "openlibrary"
  },
  "pets-rule-8": {
    "pages": 96,
    "isbn13": "9781546180258",
    "isbn10": "1546180257",
    "publisher": "Scholastic, Incorporated",
    "published": "2025",
    "source": "openlibrary"
  },
  "pixie-tricks-2": {
    "pages": 96,
    "isbn13": "9798855143065",
    "isbn10": "133862783X",
    "publisher": "Scholastic Paperbacks",
    "published": "2000",
    "source": "openlibrary"
  },
  "pixie-tricks-4": {
    "pages": 92,
    "isbn13": "9781338627879",
    "isbn10": "1338627872",
    "publisher": "Bound to Stay Bound Books",
    "published": "2000",
    "source": "openlibrary"
  },
  "pixie-tricks-5": {
    "pages": 92,
    "isbn13": "9780613322683",
    "isbn10": "0439179815",
    "publisher": "Rebound by Sagebrush",
    "published": "2000",
    "source": "openlibrary"
  },
  "press-start-1": {
    "isbn13": "9781338035254",
    "isbn10": "1338035258",
    "publisher": "Scholastic, Incorporated",
    "published": "2016",
    "source": "openlibrary"
  },
  "press-start-3": {
    "pages": 72,
    "isbn13": "9781338034790",
    "isbn10": "1338034790",
    "published": "2017",
    "synopsis": "Super Rabbit Boy is racing in the Super Grand Prix car race--but among the other racers is King Viking and his team of cheaters, and they will do anything to win.",
    "source": "openlibrary"
  },
  "press-start-4": {
    "pages": 76,
    "isbn13": "9781338034752",
    "isbn10": "1338034766",
    "publisher": "Scholastic Inc.",
    "published": "2018",
    "synopsis": "Super Rabbit Boy falls down a pipe and discovers himself in a mirror reality where everyone good is now evil, including his mirror self, Super Rabbit Boss, and he must make friends with King Viking (now one of the good guys) and somehow defeat his alter ego in order to save this world--and somehow find a way back to his own reality.",
    "source": "openlibrary"
  },
  "press-start-5": {
    "pages": 76,
    "isbn13": "9781338239621",
    "isbn10": "1338239627",
    "publisher": "Scholastic, Incorporated",
    "published": "2018",
    "synopsis": "Help! Meanie King Viking is causing trouble out in space! Super Rabbit Boy knows he can stop him. But can he fly a wobbly Level 1 rocketship, stop an army of space robots, and find King Viking?",
    "source": "openlibrary"
  },
  "press-start-6": {
    "pages": 80,
    "isbn13": "9781338239782",
    "isbn10": "1338239783",
    "publisher": "Branches",
    "published": "2018",
    "source": "openlibrary"
  },
  "press-start-7": {
    "pages": 80,
    "isbn13": "9781338239812",
    "isbn10": "1338239813",
    "publisher": "Scholastic Inc.",
    "published": "2019",
    "source": "openlibrary"
  },
  "press-start-8": {
    "pages": 80,
    "isbn13": "9781338239843",
    "isbn10": "1338239856",
    "publisher": "Scholastic, Incorporated",
    "published": "2019",
    "source": "openlibrary"
  },
  "press-start-9": {
    "pages": 80,
    "isbn13": "9781338568981",
    "isbn10": "1338568965",
    "publisher": "Scholastic, Incorporated",
    "published": "2020",
    "source": "openlibrary"
  },
  "press-start-10": {
    "pages": 80,
    "isbn13": "9781338568998",
    "isbn10": "133856899X",
    "publisher": "Scholastic, Incorporated",
    "published": "2021",
    "source": "openlibrary"
  },
  "press-start-11": {
    "pages": 80,
    "isbn13": "9781338569025",
    "isbn10": "1338569023",
    "publisher": "Scholastic, Incorporated",
    "published": "2021",
    "source": "openlibrary"
  },
  "press-start-12": {
    "isbn13": "9781536475692",
    "isbn10": "1536475696",
    "publisher": "Scholastic, Incorporated",
    "published": "2022",
    "source": "openlibrary"
  },
  "press-start-13": {
    "pages": 80,
    "isbn13": "9781338828764",
    "isbn10": "1338828762",
    "publisher": "Scholastic, Incorporated",
    "published": "2023",
    "source": "openlibrary"
  },
  "press-start-14": {
    "pages": 140,
    "isbn13": "9798855042351",
    "isbn10": "1338828797",
    "publisher": "Scholastic, Incorporated",
    "published": "2023",
    "source": "openlibrary"
  },
  "press-start-15": {
    "isbn13": "9781339042787",
    "isbn10": "1339042789",
    "publisher": "Scholastic, Incorporated",
    "published": "2024",
    "source": "openlibrary"
  },
  "press-start-16": {
    "pages": 80,
    "isbn13": "9781546110446",
    "isbn10": "1546110445",
    "publisher": "Scholastic, Incorporated",
    "published": "2025",
    "source": "openlibrary"
  },
  "silver-pony-ranch-1": {
    "pages": 93,
    "isbn13": "9780545797665",
    "isbn10": "0606377719",
    "publisher": "Turtleback Books",
    "published": "2015",
    "synopsis": "Nine-year-old Tori is thrilled to be spending the summer at her grandmother's ranch, even if she has to share a room with her younger sister Miranda, who is eight--there is a beautiful, but very nervous, new pony called Jewel that she would love to ride, but her grandmother feels that this pony is just too much for a child.",
    "source": "openlibrary"
  },
  "silver-pony-ranch-2": {
    "pages": 93,
    "isbn13": "9780545797719",
    "isbn10": "0545797721",
    "publisher": "Turtleback Books",
    "published": "2016",
    "synopsis": "While staying at their grandmother's ranch, sisters Tori and Miranda are practicing to compete in different events at the local horse show--but Ashley, a rude and conceited girl who is stabling her pony at the ranch, is constantly criticizing everthing, their costumes, their ponies, Jewel and Buttercup, and generally draining the fun out of the summer.",
    "source": "openlibrary"
  },
  "sports-zone-3": {
    "pages": 96,
    "isbn13": "9798295205446",
    "publisher": "Scholastic, Incorporated",
    "published": "2026",
    "source": "openlibrary"
  },
  "the-binder-of-doom-1": {
    "pages": 90,
    "isbn13": "9798855029048",
    "isbn10": "1536454826",
    "publisher": "Scholastic, Incorporated",
    "published": "2019",
    "source": "openlibrary"
  },
  "the-binder-of-doom-2": {
    "pages": 96,
    "isbn13": "9781338314694",
    "isbn10": "1338314696",
    "publisher": "Scholastic, Incorporated",
    "published": "2019",
    "source": "openlibrary"
  },
  "the-binder-of-doom-3": {
    "isbn13": "9781536461503",
    "isbn10": "1338314750",
    "publisher": "Scholastic, Incorporated",
    "published": "2020",
    "source": "openlibrary"
  },
  "the-binder-of-doom-4": {
    "pages": 96,
    "isbn13": "9781338314779",
    "isbn10": "1338314769",
    "publisher": "Scholastic, Incorporated",
    "published": "2020",
    "source": "openlibrary"
  },
  "the-notebook-of-doom-1": {
    "pages": 89,
    "isbn13": "9781532142727",
    "isbn10": "1532142722",
    "publisher": "Chapter Books",
    "published": "2018",
    "source": "openlibrary"
  },
  "the-notebook-of-doom-2": {
    "pages": 96,
    "isbn13": "9780545493253",
    "isbn10": "0545493250",
    "publisher": "Scholastic Inc.",
    "published": "2013",
    "source": "openlibrary"
  },
  "the-notebook-of-doom-3": {
    "pages": 88,
    "isbn13": "9780545552981",
    "isbn10": "0545552982",
    "publisher": "Scholastic Inc.",
    "published": "2013",
    "synopsis": "The latest monsters threatening Stermont Elementary are shadowy shapeshifters that attach themselves to people, eat their shadows, and block out all light--but before he can think of a way to deal with them, Alexander has to deal with a startling revelation from his friend Nikki. Alexander goes up against shadow smashers. These monsters jump from shadow to shadow, causing problems all over town.",
    "source": "openlibrary"
  },
  "the-notebook-of-doom-4": {
    "pages": 89,
    "isbn13": "9781532142758",
    "isbn10": "1532142757",
    "publisher": "Chapter Books",
    "published": "2018",
    "source": "openlibrary"
  },
  "the-notebook-of-doom-5": {
    "pages": 93,
    "isbn13": "9780545698955",
    "isbn10": "1532142765",
    "publisher": "Turtleback Books",
    "published": "2014",
    "synopsis": "When Alexander and his friends find a very large footprint and piles of candy everywhere, they realize the school is being threatened by a Piñata-saurus Rex, a sweet-tasting monster that likes to smash things. Book #5 When Alexander and his friends find a very large footprint and piles of candy everywhere, they realize the school is being threatened by a Piñata-saurus Rex, a sweet-tasting monster who likes to smash things--and they find that the solution may be as near as a broken ant farm.",
    "source": "openlibrary"
  },
  "the-notebook-of-doom-6": {
    "isbn13": "9780545699013",
    "isbn10": "1532142773",
    "publisher": "Spotlight",
    "published": "2014",
    "source": "openlibrary"
  },
  "the-notebook-of-doom-7": {
    "pages": 88,
    "isbn13": "9780545795500",
    "isbn10": "0545795508",
    "published": "2015",
    "synopsis": "It is a very hot summer in Stermont, and Alexander and his friends are at Camp Gloamy in the mountains, but even here there are monsters--specifically zombie snowmen called snombies who want to freeze the young monster-hunters. It is a very hot summer in Stermont, and Alexander and his friends are at Camp Gloamy in the mountains. But even here there are monsters, specifically zombie snowmen called snombies that want to freeze the young monster-hunters. Book #7",
    "source": "openlibrary"
  },
  "the-notebook-of-doom-8": {
    "pages": 96,
    "isbn13": "9780545795555",
    "isbn10": "0545795559",
    "publisher": "Scholastic, Incorporated",
    "published": "2015",
    "source": "openlibrary"
  },
  "the-notebook-of-doom-9": {
    "pages": 88,
    "isbn13": "9781532142802",
    "isbn10": "1532142803",
    "publisher": "Chapter Books",
    "published": "2018",
    "source": "openlibrary"
  },
  "the-notebook-of-doom-10": {
    "pages": 96,
    "isbn13": "9780606388054",
    "isbn10": "0606388052",
    "publisher": "Turtleback Books",
    "published": "2016",
    "source": "openlibrary"
  },
  "the-notebook-of-doom-11": {
    "pages": 93,
    "isbn13": "9781338034493",
    "isbn10": "1536400394",
    "publisher": "Scholastic, Incorporated",
    "published": "2016",
    "synopsis": "Everything stinks! Alexander, Rip, and Nikki aren't in the same class anymore. The monster notebook is missing. And a HONKing monster is sliming Stermont! Plus, actual smelly stuff is going missing all over town. Could all of these stinky things be connected? The S.S.M.P. will have to sniff out their latest monster!",
    "source": "openlibrary"
  },
  "the-notebook-of-doom-12": {
    "pages": 96,
    "isbn13": "9781532142833",
    "isbn10": "060640192X",
    "publisher": "Turtleback Books",
    "published": "2017",
    "source": "openlibrary"
  },
  "the-notebook-of-doom-13": {
    "pages": 96,
    "isbn13": "9781338034578",
    "isbn10": "133803457X",
    "publisher": "Scholastic Inc.",
    "published": "2017",
    "source": "openlibrary"
  },
  "the-party-diaries-1": {
    "pages": 71,
    "isbn13": "9781338799620",
    "isbn10": "1338799614",
    "publisher": "Scholastic, Incorporated",
    "published": "2023",
    "source": "openlibrary"
  },
  "the-party-diaries-2": {
    "pages": 76,
    "isbn13": "9798855116960",
    "isbn10": "1338799819",
    "publisher": "Bound to Stay Bound Books",
    "published": "2023",
    "source": "openlibrary"
  },
  "the-party-diaries-3": {
    "pages": 76,
    "isbn13": "9798855116984",
    "isbn10": "1536482366",
    "publisher": "Unknown Publisher",
    "published": "2023",
    "source": "openlibrary"
  },
  "the-party-diaries-4": {
    "isbn13": "9781338896916",
    "isbn10": "1536484784",
    "publisher": "Scholastic, Incorporated",
    "published": "2024",
    "source": "openlibrary"
  },
  "the-party-diaries-5": {
    "pages": 80,
    "isbn13": "9781546137573",
    "isbn10": "1536491497",
    "publisher": "Scholastic, Incorporated",
    "published": "2025",
    "source": "openlibrary"
  },
  "thea-stilton-6": {
    "isbn13": "9788856645880",
    "isbn10": "144312785X",
    "publisher": "Piemme",
    "published": "2010",
    "synopsis": "To catch a thief! The Thea Sisters are off to Japan on a cultural exchange program. While they're busy exploring Kyoto and admiring the beautiful cherry blossoms, a valuable item is stolen, from their friend Kumi's family. Will the five mice be able to catch the thief?",
    "source": "openlibrary"
  },
  "thea-stilton-30": {
    "isbn13": "9789352759835",
    "isbn10": "9352759834",
    "published": "2019",
    "source": "openlibrary"
  },
  "thea-stilton-32": {
    "pages": 168,
    "isbn13": "9798855130546",
    "isbn10": "1544448392",
    "publisher": "Scholastic, Incorporated",
    "published": "2020",
    "source": "openlibrary"
  },
  "thea-stilton-34": {
    "pages": 170,
    "isbn13": "9781713770947",
    "isbn10": "1713770946",
    "publisher": "Bound to Stay Bound Books",
    "published": "2021",
    "source": "openlibrary"
  },
  "unicorn-diaries-1": {
    "pages": 80,
    "isbn13": "9781338323320",
    "isbn10": "1338670085",
    "publisher": "Scholastic, Incorporated",
    "published": "2019",
    "source": "openlibrary"
  },
  "unicorn-diaries-2": {
    "pages": 80,
    "isbn13": "9781338323405",
    "isbn10": "1338323385",
    "publisher": "Scholastic, Incorporated",
    "published": "2020",
    "source": "openlibrary"
  },
  "unicorn-diaries-3": {
    "pages": 80,
    "isbn13": "9781338323429",
    "isbn10": "1338323431",
    "publisher": "Penworthy Company, LLC, The",
    "published": "2020",
    "source": "openlibrary"
  },
  "unicorn-diaries-4": {
    "isbn13": "9781536477665",
    "isbn10": "1536477664",
    "publisher": "Scholastic, Incorporated",
    "published": "2023",
    "source": "openlibrary"
  },
  "unicorn-diaries-5": {
    "pages": 80,
    "isbn13": "9781338745542",
    "isbn10": "1338745557",
    "publisher": "Scholastic, Incorporated",
    "published": "2021",
    "source": "openlibrary"
  },
  "unicorn-diaries-6": {
    "pages": 80,
    "isbn13": "9781338745627",
    "isbn10": "1338745638",
    "publisher": "Scholastic Inc.",
    "published": "2021",
    "source": "openlibrary"
  },
  "unicorn-diaries-8": {
    "pages": 80,
    "isbn13": "9781338745665",
    "isbn10": "1338745662",
    "publisher": "Scholastic, Incorporated",
    "published": "2023",
    "source": "openlibrary"
  },
  "unicorn-diaries-9": {
    "pages": 80,
    "isbn13": "9781338880366",
    "isbn10": "153648234X",
    "publisher": "Scholastic Inc.",
    "published": "2023",
    "source": "openlibrary"
  },
  "unicorn-diaries-10": {
    "isbn13": "9781338880441",
    "isbn10": "1338880438",
    "publisher": "Scholastic, Incorporated",
    "published": "2024",
    "source": "openlibrary"
  }
};
