/* ============================================================
   Reyhan's Reading List — data file
   ------------------------------------------------------------
   HOW TO ADD A BOOK:
   1. Append one object to the BOOKS array below (copy an
      existing one as a template). Keep the id a lowercase slug.
      Covers load automatically from Open Library / Google Books
      via coverIsbn — the coverFile field is legacy and unused.
   2. If it's a brand-new series, add its name to SERIES_ORDER,
      give it a color in SERIES_COLORS, and add its details to
      SERIES_META (tags power the filter chips and search).
   3. WISHLIST: to show a book in the "Up Next" row before it's
      read, add `status: "upNext"` to its object (dateRead,
      rating, and pages may be omitted). Once finished, delete
      the status field and fill in dateRead + displayDateRead.
   The book counts and stats update automatically.
   Also update the reading log tables in /README.md.
   ============================================================ */

const SERIES_ORDER = [
  "Frozen",
  "Anna & Elsa",
  "Dragon Masters",
  "Llama Quest",
  "Kwame's Magic Quest",
  "Pets Rule!",
  "The Last Firehawk",
  "Pixie Tricks",
  "Coral Keepers",
];

/* Accent color per series, used by the no-cover fallback card. */
const SERIES_COLORS = {
  "Frozen": "#4aa8d8",
  "Anna & Elsa": "#7b6fd0",
  "Dragon Masters": "#c0392b",
  "Llama Quest": "#27ae60",
  "Kwame's Magic Quest": "#16a085",
  "Pets Rule!": "#e67e22",
  "The Last Firehawk": "#d35400",
  "Pixie Tricks": "#9b59b6",
  "Coral Keepers": "#00b8a9",
};

/* Series-level metadata: illustrator, reading level, tags, and
   "you might like next" suggestions shown in the detail modal. */
const SERIES_META = {
  "Frozen": {
    "illustrator": "RH Disney (Disney Storybook Art Team film art)",
    "ageRange": "Ages 8–12",
    "gradeLevel": "Grades 3–7",
    "lexile": null,
    "tags": [
      "Fairy Tale",
      "Sisters",
      "Movie Tie-In",
      "Fantasy"
    ],
    "suggestions": [
      {
        "title": "Unicorn Academy",
        "author": "Julie Sykes",
        "blurb": "If you loved Elsa's icy magic and big-hearted friendships, this sparkly school for unicorn riders delivers the same magic-and-loyalty combo.",
        "amazonUsUrl": "https://www.amazon.com/Unicorn-Academy-1-Sophia-Rainbow/dp/1984850822",
        "amazonCaUrl": "https://www.amazon.ca/dp/1984850822"
      },
      {
        "title": "Heidi Heckelbeck",
        "author": "Wanda Coven",
        "blurb": "A regular-seeming girl hiding magical powers, just like Elsa, in short cozy chapters perfect after a Disney novelization.",
        "amazonUsUrl": "https://www.amazon.com/Heidi-Heckelbeck-Secret-Wanda-Coven/dp/1442435658",
        "amazonCaUrl": "https://www.amazon.ca/dp/1442435658"
      },
      {
        "title": "Isadora Moon",
        "author": "Harriet Muncaster",
        "blurb": "A half-fairy, half-vampire heroine learning to embrace being different — the same be-yourself heart that makes Frozen special.",
        "amazonUsUrl": "https://www.amazon.com/Isadora-Moon-School-Harriet-Muncaster/dp/0399558217",
        "amazonCaUrl": "https://www.amazon.ca/dp/0399558217"
      }
    ]
  },
  "Anna & Elsa": {
    "illustrator": "Bill Robinson",
    "ageRange": "Ages 6–9",
    "gradeLevel": "Grades 1–4",
    "lexile": "560L",
    "tags": [
      "Fantasy",
      "Sisters",
      "Movie Tie-In",
      "Adventure"
    ],
    "suggestions": [
      {
        "title": "Unicorn Academy",
        "author": "Julie Sykes",
        "blurb": "More magical kingdom adventures with brave girls and loyal companions, at the same easy chapter-book level as Anna & Elsa.",
        "amazonUsUrl": "https://www.amazon.com/Unicorn-Academy-1-Sophia-Rainbow/dp/1984850822",
        "amazonCaUrl": "https://www.amazon.ca/dp/1984850822"
      },
      {
        "title": "Owl Diaries",
        "author": "Rebecca Elliott",
        "blurb": "If you like Anna and Elsa solving problems together, Eva the owl's friendship-first adventures have the same warm, kind spirit.",
        "amazonUsUrl": "https://www.amazon.com/Evas-Treetop-Festival-Branches-Diaries/dp/0545683629",
        "amazonCaUrl": "https://www.amazon.ca/dp/0545683629"
      },
      {
        "title": "Mermaid Tales",
        "author": "Debbie Dadey",
        "blurb": "Another enchanted kingdom — this one underwater — where friends use a little magic and a lot of heart to save the day.",
        "amazonUsUrl": "https://www.amazon.com/Trouble-Trident-Academy-Mermaid-Tales/dp/1442429801",
        "amazonCaUrl": "https://www.amazon.ca/dp/1442429801"
      }
    ]
  },
  "Dragon Masters": {
    "illustrator": "Graham Howells & Matt Loveridge",
    "ageRange": "Ages 6–8",
    "gradeLevel": "Grades 1–3",
    "lexile": "510L",
    "tags": [
      "Fantasy",
      "Dragons",
      "Adventure"
    ],
    "suggestions": [
      {
        "title": "Dragon Girls",
        "author": "Maddy Mara",
        "blurb": "If training dragons with Drake is your thing, imagine BEING the dragon — glitter-breathing girls protect a magic forest.",
        "amazonUsUrl": "https://www.amazon.com/Azmina-Gold-Glitter-Dragon-Girls/dp/1338680633",
        "amazonCaUrl": "https://www.amazon.ca/dp/1338680633"
      },
      {
        "title": "Press Start!",
        "author": "Thomas Flintham",
        "blurb": "Same fast-paced Branches action as Dragon Masters, but with a video-game hero battling a robot army level by level.",
        "amazonUsUrl": "https://www.amazon.com/Super-Rabbit-Branches-Press-Start/dp/1338034715",
        "amazonCaUrl": "https://www.amazon.ca/dp/1338034715"
      },
      {
        "title": "The Notebook of Doom",
        "author": "Troy Cummings",
        "blurb": "A monster-battling Branches series with the same page-turning missions and creature-guide fun as the Dragon Masters world.",
        "amazonUsUrl": "https://www.amazon.com/Rise-Balloon-Goons-Branches-Notebook/dp/0545493234",
        "amazonCaUrl": "https://www.amazon.ca/dp/0545493234"
      }
    ]
  },
  "Llama Quest": {
    "illustrator": "Kay Davault",
    "ageRange": "Ages 6–9",
    "gradeLevel": "Grades 1–4",
    "lexile": "720L",
    "tags": [
      "Fantasy",
      "Quest",
      "Magical Animals",
      "Humor"
    ],
    "suggestions": [
      {
        "title": "Zoey and Sassafras",
        "author": "Asia Citro",
        "blurb": "If you love questing with a magical talking llama, Zoey's backyard barn full of magical creatures needing help is a perfect next stop.",
        "amazonUsUrl": "https://www.amazon.com/Dragons-Marshmallows-Zoey-Sassafras-Citro/dp/1943147094",
        "amazonCaUrl": "https://www.amazon.ca/dp/1943147094"
      },
      {
        "title": "Dragon Girls",
        "author": "Maddy Mara",
        "blurb": "Another save-the-magical-kingdom quest with animal magic and a mission in every book, right at the Llama Quest level.",
        "amazonUsUrl": "https://www.amazon.com/Azmina-Gold-Glitter-Dragon-Girls/dp/1338680633",
        "amazonCaUrl": "https://www.amazon.ca/dp/1338680633"
      },
      {
        "title": "Press Start!",
        "author": "Thomas Flintham",
        "blurb": "Lucy the llama's silly-but-brave energy matches Super Rabbit Boy's level-hopping quests to save Animal Town.",
        "amazonUsUrl": "https://www.amazon.com/Super-Rabbit-Branches-Press-Start/dp/1338034715",
        "amazonCaUrl": "https://www.amazon.ca/dp/1338034715"
      }
    ]
  },
  "Kwame's Magic Quest": {
    "illustrator": "Natasha Nayo",
    "ageRange": "Ages 6–8",
    "gradeLevel": "Grades 1–3",
    "lexile": "600L",
    "tags": [
      "Fantasy",
      "Magic School",
      "Adventure",
      "African Cultures"
    ],
    "suggestions": [
      {
        "title": "Zoey and Sassafras",
        "author": "Asia Citro",
        "blurb": "Like Kwame, Zoey figures out magic step by step — she uses science experiments to help magical creatures in trouble.",
        "amazonUsUrl": "https://www.amazon.com/Dragons-Marshmallows-Zoey-Sassafras-Citro/dp/1943147094",
        "amazonCaUrl": "https://www.amazon.ca/dp/1943147094"
      },
      {
        "title": "Heidi Heckelbeck",
        "author": "Wanda Coven",
        "blurb": "Another kid balancing school life with secret magic powers, with the same warm humor about fitting in and finding your strength.",
        "amazonUsUrl": "https://www.amazon.com/Heidi-Heckelbeck-Secret-Wanda-Coven/dp/1442435658",
        "amazonCaUrl": "https://www.amazon.ca/dp/1442435658"
      },
      {
        "title": "Press Start!",
        "author": "Thomas Flintham",
        "blurb": "Same fast, fully illustrated Branches format with an underdog hero leveling up against bigger and bigger challenges.",
        "amazonUsUrl": "https://www.amazon.com/Super-Rabbit-Branches-Press-Start/dp/1338034715",
        "amazonCaUrl": "https://www.amazon.ca/dp/1338034715"
      }
    ]
  },
  "Pets Rule!": {
    "illustrator": "Wendy Tan Shiau Wei",
    "ageRange": "Ages 6–8",
    "gradeLevel": "Grades 1–3",
    "lexile": "570L",
    "tags": [
      "Humor",
      "Animals",
      "Villainy"
    ],
    "suggestions": [
      {
        "title": "The Bad Guys",
        "author": "Aaron Blabey",
        "blurb": "If Ember's world-domination schemes crack you up, this gang of 'villainous' animals trying to be heroes is comedy gold.",
        "amazonUsUrl": "https://www.amazon.com/Bad-Guys/dp/0545912407",
        "amazonCaUrl": "https://www.amazon.ca/dp/0545912407"
      },
      {
        "title": "Diary of a Pug",
        "author": "Kyla May",
        "blurb": "Another hilarious dog with a big personality narrating his own adventures, in the same illustrated Branches style as Pets Rule!.",
        "amazonUsUrl": "https://www.amazon.com/Pug-Blasts-Off-Branches-Diary/dp/1338530038",
        "amazonCaUrl": "https://www.amazon.ca/dp/1338530038"
      },
      {
        "title": "InvestiGators",
        "author": "John Patrick Green",
        "blurb": "Absurd animal heroes, over-the-top villains, and nonstop jokes — a graphic-novel step up with the same goofy energy.",
        "amazonUsUrl": "https://www.amazon.com/InvestiGators-John-Patrick-Green/dp/1250219957",
        "amazonCaUrl": "https://www.amazon.ca/dp/1250219957"
      }
    ]
  },
  "The Last Firehawk": {
    "illustrator": "Jeremy Norton",
    "ageRange": "Ages 6–8",
    "gradeLevel": "Grades 1–3",
    "lexile": "560L",
    "tags": [
      "Fantasy",
      "Animals",
      "Quest",
      "Adventure"
    ],
    "suggestions": [
      {
        "title": "The Notebook of Doom",
        "author": "Troy Cummings",
        "blurb": "If you like Tag and Skyla battling Thorn's dark forces, Alexander's monster-of-the-book missions bring the same brave-kid thrills.",
        "amazonUsUrl": "https://www.amazon.com/Rise-Balloon-Goons-Branches-Notebook/dp/0545493234",
        "amazonCaUrl": "https://www.amazon.ca/dp/0545493234"
      },
      {
        "title": "Dragon Girls",
        "author": "Maddy Mara",
        "blurb": "Another magical-creature quest to protect an enchanted land from a shadowy threat, one mission per book.",
        "amazonUsUrl": "https://www.amazon.com/Azmina-Gold-Glitter-Dragon-Girls/dp/1338680633",
        "amazonCaUrl": "https://www.amazon.ca/dp/1338680633"
      },
      {
        "title": "Owl Diaries",
        "author": "Rebecca Elliott",
        "blurb": "More adventures starring plucky owls and woodland friends, in a gentler diary style that Firehawk fans find cozy.",
        "amazonUsUrl": "https://www.amazon.com/Evas-Treetop-Festival-Branches-Diaries/dp/0545683629",
        "amazonCaUrl": "https://www.amazon.ca/dp/0545683629"
      }
    ]
  },
  "Pixie Tricks": {
    "illustrator": "Xavier Bonet",
    "ageRange": "Ages 6–8",
    "gradeLevel": "Grades 1–3",
    "lexile": "500L",
    "tags": [
      "Fantasy",
      "Fairies",
      "Humor",
      "Adventure"
    ],
    "suggestions": [
      {
        "title": "Isadora Moon",
        "author": "Harriet Muncaster",
        "blurb": "If mischievous fairies are your favorite, this half-fairy, half-vampire heroine brings the same sparkly, funny magic.",
        "amazonUsUrl": "https://www.amazon.com/Isadora-Moon-School-Harriet-Muncaster/dp/0399558217",
        "amazonCaUrl": "https://www.amazon.ca/dp/0399558217"
      },
      {
        "title": "Heidi Heckelbeck",
        "author": "Wanda Coven",
        "blurb": "Like Violet, Heidi is an ordinary kid juggling everyday life with secret magic — and things go wrong in funny ways.",
        "amazonUsUrl": "https://www.amazon.com/Heidi-Heckelbeck-Secret-Wanda-Coven/dp/1442435658",
        "amazonCaUrl": "https://www.amazon.ca/dp/1442435658"
      },
      {
        "title": "Zoey and Sassafras",
        "author": "Asia Citro",
        "blurb": "Another clever girl handling magical creatures that show up in her own backyard, one tricky problem at a time.",
        "amazonUsUrl": "https://www.amazon.com/Dragons-Marshmallows-Zoey-Sassafras-Citro/dp/1943147094",
        "amazonCaUrl": "https://www.amazon.ca/dp/1943147094"
      }
    ]
  },
  "Coral Keepers": {
    "illustrator": "Paul Kellam",
    "ageRange": "Ages 6–8",
    "gradeLevel": "Grades 1–3",
    "lexile": "600L",
    "tags": [
      "Fantasy",
      "Mermaids",
      "Ocean",
      "Adventure"
    ],
    "suggestions": [
      {
        "title": "Mermaid Tales",
        "author": "Debbie Dadey",
        "blurb": "If you love Finn's underwater queendom, Shelly's adventures at mermaid school in Trident City are a natural next dive.",
        "amazonUsUrl": "https://www.amazon.com/Trouble-Trident-Academy-Mermaid-Tales/dp/1442429801",
        "amazonCaUrl": "https://www.amazon.ca/dp/1442429801"
      },
      {
        "title": "Dragon Girls",
        "author": "Maddy Mara",
        "blurb": "Magical girls with creature powers defending their realm from a scheming villain — Coral Keepers energy, on dragon wings.",
        "amazonUsUrl": "https://www.amazon.com/Azmina-Gold-Glitter-Dragon-Girls/dp/1338680633",
        "amazonCaUrl": "https://www.amazon.ca/dp/1338680633"
      },
      {
        "title": "Unicorn Academy",
        "author": "Julie Sykes",
        "blurb": "Another magic academy where a girl must master her powers with friends to stop a threat to the kingdom.",
        "amazonUsUrl": "https://www.amazon.com/Unicorn-Academy-1-Sophia-Rainbow/dp/1984850822",
        "amazonCaUrl": "https://www.amazon.ca/dp/1984850822"
      }
    ]
  }
};

const BOOKS = [
  {
    "id": "frozen-junior-novelization",
    "title": "Frozen: The Junior Novelization",
    "series": "Frozen",
    "seriesNumber": null,
    "author": "Sarah Nathan",
    "dateRead": "2026-02-15",
    "displayDateRead": "February 2026",
    "goodreadsRating": 4.17,
    "synopsis": "This chapter-book retelling of the hit movie follows fearless Anna after her sister Elsa's icy powers accidentally plunge the kingdom of Arendelle into an endless winter. Anna sets off into the mountains with rugged ice harvester Kristoff, his loyal reindeer Sven, and a cheerful snowman named Olaf to find Elsa and bring back summer. Along the way she discovers that nothing is stronger than the love between sisters.",
    "coverFile": "covers/frozen-junior-novelization.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/0736431187",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/0736431187",
    "amazonCaExact": true,
    "coverIsbn": "0736431187",
    "goodreadsUrl": "https://www.goodreads.com/book/show/18857202-frozen",
    "pages": 128
  },
  {
    "id": "anna-elsa-03",
    "title": "A Warm Welcome",
    "series": "Anna & Elsa",
    "seriesNumber": 3,
    "author": "Erica David",
    "dateRead": "2026-02-15",
    "displayDateRead": "February 2026",
    "goodreadsRating": 4.1,
    "synopsis": "Olaf hears amazing news: a faraway land has a 'summer queen' with heat magic, whose kingdom is stuck in endless summer. Olaf thinks that sounds wonderful, but Anna and Elsa worry the queen might be trapped, just like Arendelle once was in eternal winter. The sisters journey to the desert kingdom of Eldora, where they find a surprise — and a warm new friendship.",
    "coverFile": "covers/anna-elsa-03.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/0736432892",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/0736432892",
    "amazonCaExact": true,
    "coverIsbn": "0736432892",
    "goodreadsUrl": "https://www.goodreads.com/book/show/22889793-a-warm-welcome",
    "pages": 128
  },
  {
    "id": "dragon-masters-01",
    "title": "Rise of the Earth Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 1,
    "author": "Tracey West",
    "dateRead": "2026-03-15",
    "displayDateRead": "March 2026",
    "goodreadsRating": 4.26,
    "synopsis": "Eight-year-old Drake is scooped up from his family's onion farm and brought to King Roland's castle, where he learns he has been chosen to be a Dragon Master. Training alongside new friends Ana, Rori, and Bo, Drake is paired with an Earth Dragon he names Worm. But Worm doesn't breathe fire or fly, and Drake starts to wonder if his dragon has any powers at all -- until danger strikes and Worm reveals a surprising secret.",
    "coverFile": "covers/dragon-masters-01.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/0545646235",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/0545646235",
    "amazonCaExact": true,
    "coverIsbn": "0545646235",
    "goodreadsUrl": "https://www.goodreads.com/book/show/20578964-rise-of-the-earth-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-02",
    "title": "Saving the Sun Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 2,
    "author": "Tracey West",
    "dateRead": "2026-03-15",
    "displayDateRead": "March 2026",
    "goodreadsRating": 4.34,
    "synopsis": "Ana's Sun Dragon, Kepri, suddenly grows weak and sick, and nobody at the castle can figure out why. Drake and the other Dragon Masters set out to help their friend and find a cure. Their search leads them all the way to the Land of Pyramids, where they uncover a surprising secret about where Kepri comes from and what she needs to get well.",
    "coverFile": "covers/dragon-masters-02.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/0545646251",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/0545646251",
    "amazonCaExact": true,
    "coverIsbn": "0545646251",
    "goodreadsUrl": "https://www.goodreads.com/book/show/20897351-saving-the-sun-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-03",
    "title": "Secret of the Water Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 3,
    "author": "Tracey West",
    "dateRead": "2026-03-15",
    "displayDateRead": "March 2026",
    "goodreadsRating": 4.38,
    "synopsis": "Someone is trying to steal the magical Dragon Stone -- and all the clues point to Drake's friend Bo! Drake can't believe a fellow Dragon Master would ever be a thief. As he digs into the mystery, he discovers that Bo's family is in terrible danger, and the friends must team up with Bo's Water Dragon, Shu, to outsmart the real villain.",
    "coverFile": "covers/dragon-masters-03.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/0545646286",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/0545646286",
    "amazonCaExact": true,
    "coverIsbn": "0545646286",
    "goodreadsUrl": "https://www.goodreads.com/book/show/22749541-secret-of-the-water-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-04",
    "title": "Power of the Fire Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 4,
    "author": "Tracey West",
    "dateRead": "2026-03-15",
    "displayDateRead": "March 2026",
    "goodreadsRating": 4.41,
    "synopsis": "Most of the Dragon Masters get to visit Queen Rose's faraway kingdom, but Drake and Rori are stuck staying behind to guard the castle. Then the evil wizard Maldred attacks -- riding a fearsome four-headed dragon! Rori and her Fire Dragon, Vulcan, along with Drake and Worm, must find the courage and teamwork to defend their home.",
    "coverFile": "covers/dragon-masters-04.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/0545646316",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/0545646316",
    "amazonCaExact": true,
    "coverIsbn": "0545646316",
    "goodreadsUrl": "https://www.goodreads.com/book/show/24944997-power-of-the-fire-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-05",
    "title": "Song of the Poison Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 5,
    "author": "Tracey West",
    "dateRead": "2026-03-15",
    "displayDateRead": "March 2026",
    "goodreadsRating": 4.38,
    "synopsis": "A new Dragon Master named Petra arrives at the castle, but she acts like a know-it-all and won't even try to bond with her four-headed Poison Dragon. Then a terrible accident leaves King Roland poisoned, and time is running out. Petra must finally open her heart to her dragon and unlock its amazing hidden power to save the king.",
    "coverFile": "covers/dragon-masters-05.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/054591387X",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/054591387X",
    "amazonCaExact": true,
    "coverIsbn": "054591387X",
    "goodreadsUrl": "https://www.goodreads.com/book/show/26892085-song-of-the-poison-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-06",
    "title": "Flight of the Moon Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 6,
    "author": "Tracey West",
    "dateRead": "2026-03-15",
    "displayDateRead": "March 2026",
    "goodreadsRating": 4.45,
    "synopsis": "The prime Dragon Stone is in danger, and if it fails, every Dragon Master will lose their connection to their dragon forever! Drake and his friends race to the Land of Pyramids to find the secret Pyramid of the Seven Dragons. With help from a mysterious Moon Dragon, they must complete their quest before the bond is broken for good.",
    "coverFile": "covers/dragon-masters-06.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/0545913926",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/0545913926",
    "amazonCaExact": true,
    "coverIsbn": "0545913926",
    "goodreadsUrl": "https://www.goodreads.com/book/show/29241320-flight-of-the-moon-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-07",
    "title": "Search for the Lightning Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 7,
    "author": "Tracey West",
    "dateRead": "2026-03-15",
    "displayDateRead": "March 2026",
    "goodreadsRating": 4.42,
    "synopsis": "The Dragon Masters must track down a wild Lightning Dragon that shoots dangerous sparks of energy. First they need to find the dragon's destined Dragon Master -- a boy named Carlos who has no idea dragons even exist! Drake and his friends race to help Carlos connect with the crackling dragon before an evil wizard can capture it.",
    "coverFile": "covers/dragon-masters-07.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338042882",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338042882",
    "amazonCaExact": true,
    "coverIsbn": "1338042882",
    "goodreadsUrl": "https://www.goodreads.com/book/show/37120679-search-for-the-lightning-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-08",
    "title": "Roar of the Thunder Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 8,
    "author": "Tracey West",
    "dateRead": "2026-03-15",
    "displayDateRead": "March 2026",
    "goodreadsRating": 4.39,
    "synopsis": "Lalo, the baby Lightning Dragon, has been kidnapped! The dragon-napper is Eko, the wizard Griffith's very first Dragon Master, who ran away years ago with her powerful Thunder Dragon, Neru. Now Eko plans to take every dragon in the kingdom, and Drake and his friends must rescue Lalo and stop her before it's too late.",
    "coverFile": "covers/dragon-masters-08.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338042920",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338042920",
    "amazonCaExact": true,
    "coverIsbn": "1338042920",
    "goodreadsUrl": "https://www.goodreads.com/book/show/34054689-roar-of-the-thunder-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-09",
    "title": "Chill of the Ice Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 9,
    "author": "Tracey West",
    "dateRead": "2026-04-15",
    "displayDateRead": "April 2026",
    "goodreadsRating": 4.42,
    "synopsis": "A Dragon Master named Mina arrives from the Far North Lands with scary news: a magical Ice Giant is attacking her kingdom, and her own dragon has been frozen solid. Since only fire can beat ice, Rori and her Fire Dragon, Vulcan, lead the charge. The Dragon Masters journey into the frozen north to melt the giant's icy grip and save Mina's home.",
    "coverFile": "covers/dragon-masters-09.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338169866",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338169866",
    "amazonCaExact": true,
    "coverIsbn": "1338169866",
    "goodreadsUrl": "https://www.goodreads.com/book/show/35566727-chill-of-the-ice-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-10",
    "title": "Waking the Rainbow Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 10,
    "author": "Tracey West",
    "dateRead": "2026-04-15",
    "displayDateRead": "April 2026",
    "goodreadsRating": 4.41,
    "synopsis": "Drake keeps having a strange dream about a Rainbow Dragon in trouble. Trusting the dream, he and his friends travel to the faraway kingdom of Ifri, where they discover the Rainbow Dragon trapped in a deep magical sleep inside a cave. To wake her, the Dragon Masters must get past a giant, tricky spider guarding the way.",
    "coverFile": "covers/dragon-masters-10.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338169890",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338169890",
    "amazonCaExact": true,
    "coverIsbn": "1338169890",
    "goodreadsUrl": "https://www.goodreads.com/book/show/36127327-waking-the-rainbow-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-11",
    "title": "Shine of the Silver Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 11,
    "author": "Tracey West",
    "dateRead": "2026-04-15",
    "displayDateRead": "April 2026",
    "goodreadsRating": 4.43,
    "synopsis": "The dark wizard Maldred is back, and he has put the good wizard Diego under an evil spell! Maldred is hunting for two magical keys that would let him control the Naga, an enormous dragon that sleeps deep inside the Earth. Drake, Bo, and Carlos must find the Silver Dragon guarding the first key -- and win over the dragon's stubborn Dragon Master, Jean, before Maldred beats them to it.",
    "coverFile": "covers/dragon-masters-11.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/133826365X",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/133826365X",
    "amazonCaExact": true,
    "coverIsbn": "133826365X",
    "goodreadsUrl": "https://www.goodreads.com/book/show/37825476-shine-of-the-silver-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-12",
    "title": "Treasure of the Gold Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 12,
    "author": "Tracey West",
    "dateRead": "2026-04-15",
    "displayDateRead": "April 2026",
    "goodreadsRating": 4.44,
    "synopsis": "The dark wizard Maldred is hunting for the powerful Gold Key, so Drake and Rori race to the Gold Dragon's lair to keep it out of his hands. There they meet Darma, a brand-new Dragon Master. If Maldred grabs the key, he'll be one step closer to controlling a mighty Earthquake Dragon!",
    "coverFile": "covers/dragon-masters-12.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338263684",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338263684",
    "amazonCaExact": true,
    "coverIsbn": "1338263684",
    "goodreadsUrl": "https://www.goodreads.com/book/show/39983546-treasure-of-the-gold-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-13",
    "title": "Eye of the Earthquake Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 13,
    "author": "Tracey West",
    "dateRead": "2026-04-15",
    "displayDateRead": "April 2026",
    "goodreadsRating": 4.45,
    "synopsis": "Maldred has stolen both the Gold and Silver Keys, which he needs to take control of the Naga, a huge dragon whose rumbles can shake the whole world. The Naga sleeps in a hidden temple at the center of the earth, and Maldred is already on his way there. Drake and his friends must beat him to it before terrible earthquakes tear the land apart.",
    "coverFile": "covers/dragon-masters-13.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338263714",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338263714",
    "amazonCaExact": true,
    "coverIsbn": "1338263714",
    "goodreadsUrl": "https://www.goodreads.com/book/show/40996508-eye-of-the-earthquake-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-14",
    "title": "The Land of the Spring Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 14,
    "author": "Tracey West",
    "dateRead": "2026-04-15",
    "displayDateRead": "April 2026",
    "goodreadsRating": 4.38,
    "synopsis": "A terrible earthquake has wrecked the crops in Drake's kingdom of Bracken, and only a magical Spring Dragon can make them grow again. The catch: he lives deep inside a secret fairy world full of tricks, riddles, and sneaky redcap fairies. To reach him, Drake must pass a series of tests set by a Dragon Master named Breen.",
    "coverFile": "covers/dragon-masters-14.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338263749",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338263749",
    "amazonCaExact": true,
    "coverIsbn": "1338263749",
    "goodreadsUrl": "https://www.goodreads.com/book/show/43304809-the-land-of-the-spring-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-15",
    "title": "Future of the Time Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 15,
    "author": "Tracey West",
    "dateRead": "2026-04-15",
    "displayDateRead": "April 2026",
    "goodreadsRating": 4.4,
    "synopsis": "Maldred has trapped the Dragon Master Eko with a powerful spell, and the only way to free her is with the help of a Time Dragon. But while searching for it, a sneaky imp zaps Drake back in time! Now Drake must find his way through the past if he ever wants to rescue Eko and get home.",
    "coverFile": "covers/dragon-masters-15.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338540254",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338540254",
    "amazonCaExact": true,
    "coverIsbn": "1338540254",
    "goodreadsUrl": "https://www.goodreads.com/book/show/44575127-future-of-the-time-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-16",
    "title": "Call of the Sound Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 16,
    "author": "Tracey West",
    "dateRead": "2026-05-15",
    "displayDateRead": "May 2026",
    "goodreadsRating": 4.41,
    "synopsis": "Two dueling wizards are blasting magic all over the city of Remus, and the whole place is falling apart. Drake and Petra team up with Tessa, a blind Dragon Master who shares an amazing connection with her Sound Dragon, Sono. Together they must track down a Power Crystal to end the dangerous wizard battle.",
    "coverFile": "covers/dragon-masters-16.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338540297",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338540297",
    "amazonCaExact": true,
    "coverIsbn": "1338540297",
    "goodreadsUrl": "https://www.goodreads.com/book/show/48497617-call-of-the-sound-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-17",
    "title": "Fortress of the Stone Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 17,
    "author": "Tracey West",
    "dateRead": "2026-05-15",
    "displayDateRead": "May 2026",
    "goodreadsRating": 4.42,
    "synopsis": "The evil wizard Astrid wants to become the most powerful wizard in the world, and she's gathering ingredients for a dangerous spell. Her search leads to a faraway fortress watched over by a Stone Dragon. Drake and the Dragon Masters must get there first and stop her before the spell is cast.",
    "coverFile": "covers/dragon-masters-17.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338540319",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338540319",
    "amazonCaExact": true,
    "coverIsbn": "1338540319",
    "goodreadsUrl": "https://www.goodreads.com/book/show/50370456-fortress-of-the-stone-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-18",
    "title": "Heat of the Lava Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 18,
    "author": "Tracey West",
    "dateRead": "2026-05-15",
    "displayDateRead": "May 2026",
    "goodreadsRating": 4.41,
    "synopsis": "Astrid has turned Drake's friends to stone, and she's getting closer to casting an even scarier spell. To stop her, Drake and Ana set off to find Ka, a mysterious Lava Dragon that almost everyone fears. Can they win over the fiery dragon in time to save their friends?",
    "coverFile": "covers/dragon-masters-18.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/133863545X",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/133863545X",
    "amazonCaExact": true,
    "coverIsbn": "133863545X",
    "goodreadsUrl": "https://www.goodreads.com/book/show/53578550-heat-of-the-lava-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-19",
    "title": "Wave of the Sea Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 19,
    "author": "Tracey West",
    "dateRead": "2026-05-15",
    "displayDateRead": "May 2026",
    "goodreadsRating": 4.39,
    "synopsis": "The Dragon Masters need three special dragons to undo Astrid's magic, and one of them is a Sea Dragon. Drake, Bo, and Opeli sail to the island of Kapua to search for it. Finding a dragon that lives beneath the waves is no easy job, and time is running out!",
    "coverFile": "covers/dragon-masters-19.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338635484",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338635484",
    "amazonCaExact": true,
    "coverIsbn": "1338635484",
    "goodreadsUrl": "https://www.goodreads.com/book/show/54776541-wave-of-the-sea-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-20",
    "title": "Howl of the Wind Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 20,
    "author": "Tracey West",
    "dateRead": "2026-05-15",
    "displayDateRead": "May 2026",
    "goodreadsRating": 4.41,
    "synopsis": "Drake and Rori hurry off to find a Wind Dragon, the very last dragon they need to break the False Life spell. But they discover the Wind Dragon is being held prisoner along with her Dragon Master, Quilla! Now the mission has turned into a daring rescue.",
    "coverFile": "covers/dragon-masters-20.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338635514",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338635514",
    "amazonCaExact": true,
    "coverIsbn": "1338635514",
    "goodreadsUrl": "https://www.goodreads.com/book/show/55977854-howl-of-the-wind-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-21",
    "title": "Bloom of the Flower Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 21,
    "author": "Tracey West",
    "dateRead": "2026-05-15",
    "displayDateRead": "May 2026",
    "goodreadsRating": 4.32,
    "synopsis": "A little Flower Dragon named Wildroot arrives in Bracken because his home is in danger, and he needs a Dragon Master of his own. The Dragon Stone chooses a boy named Oskar, who is bummed that his dragon isn't big and fire-breathing. Oskar and Wildroot must learn to work as a team to save the Flower Dragons from a terrible monster.",
    "coverFile": "covers/dragon-masters-21.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338776878",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338776878",
    "amazonCaExact": true,
    "coverIsbn": "1338776878",
    "goodreadsUrl": "https://www.goodreads.com/book/show/57468758-bloom-of-the-flower-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-22",
    "title": "Guarding the Invisible Dragons",
    "series": "Dragon Masters",
    "seriesNumber": 22,
    "author": "Tracey West",
    "dateRead": "2026-05-15",
    "displayDateRead": "May 2026",
    "goodreadsRating": 4.34,
    "synopsis": "A nest of baby Invisible Dragons has been found in Aragon, and their parents are nowhere to be seen. Drake, Worm, and Carlos's cousin Val set off for dangerous Dove Island to track down the missing parents and the magical fruit of the Dragon Tree. If the babies don't eat that special fruit soon, they'll lose their invisibility powers forever!",
    "coverFile": "covers/dragon-masters-22.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338776908",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338776908",
    "amazonCaExact": true,
    "coverIsbn": "1338776908",
    "goodreadsUrl": "https://www.goodreads.com/book/show/59200872-guarding-the-invisible-dragons",
    "pages": 96
  },
  {
    "id": "dragon-masters-23",
    "title": "Curse of the Shadow Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 23,
    "author": "Tracey West",
    "dateRead": "2026-06-15",
    "displayDateRead": "June 2026",
    "goodreadsRating": 4.35,
    "synopsis": "A mysterious shadow is spreading across the sky over every kingdom, and wizards around the world are losing their magic. Drake and the Dragon Masters discover that a Shadow Dragon named Chaya and his Dragon Master, Aruna, are behind the strange sky-shadow. Now they must figure out the curse driving the Shadow Dragon before darkness covers the whole world.",
    "coverFile": "covers/dragon-masters-23.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338776940",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338776940",
    "amazonCaExact": true,
    "coverIsbn": "1338776940",
    "goodreadsUrl": "https://www.goodreads.com/book/show/60758278-curse-of-the-shadow-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-24",
    "title": "Dawn of the Light Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 24,
    "author": "Tracey West",
    "dateRead": "2026-06-15",
    "displayDateRead": "June 2026",
    "goodreadsRating": 4.39,
    "synopsis": "To stop the Shadow Dragon from wrapping the whole world in shadow, Drake and Darma go looking for a Light Dragon named Lysa. Lysa's Dragon Master, Rune, who is Deaf and uses sign language, explains that they'll need a magical Star Flute to summon a Star Dragon. The only problem? The flute is hidden deep inside a dangerous labyrinth!",
    "coverFile": "covers/dragon-masters-24.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338776975",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338776975",
    "amazonCaExact": true,
    "coverIsbn": "1338776975",
    "goodreadsUrl": "https://www.goodreads.com/book/show/61779977-dawn-of-the-light-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-25",
    "title": "Legend of the Star Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 25,
    "author": "Tracey West",
    "dateRead": "2026-06-15",
    "displayDateRead": "June 2026",
    "goodreadsRating": 4.44,
    "synopsis": "Drake and his friends finally have the Star Flute, and now it's time to summon the legendary Star Dragon. In an epic showdown, the Star Dragon must battle the powerful Shadow Dragon before its sky-shadow blankets the entire world. The Dragon Masters will need teamwork and courage to bring back the light.",
    "coverFile": "covers/dragon-masters-25.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338777009",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338777009",
    "amazonCaExact": true,
    "coverIsbn": "1338777009",
    "goodreadsUrl": "https://www.goodreads.com/book/show/63898987-legend-of-the-star-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-26",
    "title": "Cave of the Crystal Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 26,
    "author": "Tracey West",
    "dateRead": "2026-06-15",
    "displayDateRead": "June 2026",
    "goodreadsRating": 4.42,
    "synopsis": "The wizard Griffith is in trouble, so Drake and Rori rush to Greenshire to find him. A boy named Llew leads them to the Crystal Cave where Griffith was last seen, but inside they're attacked by Belydor, a Crystal Dragon who doesn't trust humans. With Llew's help, the Dragon Masters must earn the dragon's trust in time to rescue Griffith.",
    "coverFile": "covers/dragon-masters-26.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1339022370",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1339022370",
    "amazonCaExact": true,
    "coverIsbn": "1339022370",
    "goodreadsUrl": "https://www.goodreads.com/book/show/124932859-cave-of-the-crystal-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-27",
    "title": "Haunting of the Ghost Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 27,
    "author": "Tracey West",
    "dateRead": "2026-06-15",
    "displayDateRead": "June 2026",
    "goodreadsRating": 4.37,
    "synopsis": "The evil wizard Zoltan has stolen the Dream Orb, which lets him sneak into the Dream World. Drake and Bo travel to his spooky castle in Gothica to get it back, and along the way they meet Dragon Master Sandor and his Ghost Dragon, Phantom. Can they brave a castle full of ghosts and stop Zoltan's plan?",
    "coverFile": "covers/dragon-masters-27.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1339022400",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1339022400",
    "amazonCaExact": true,
    "coverIsbn": "1339022400",
    "goodreadsUrl": "https://www.goodreads.com/book/show/202773002-haunting-of-the-ghost-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-28",
    "title": "Night of the Dream Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 28,
    "author": "Tracey West",
    "dateRead": "2026-07-10",
    "displayDateRead": "July 2026",
    "goodreadsRating": 4.43,
    "synopsis": "Drake and Worm chase the wicked wizard Zoltan straight into the Dream World. With help from Mamu the Dream Dragon and her Dragon Master, Kishar, they race to catch Zoltan before he can reach the powerful Dream Fountain. It's a wild adventure where dreams — and nightmares — come to life.",
    "coverFile": "covers/dragon-masters-28.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1339022435",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1339022435",
    "amazonCaExact": true,
    "coverIsbn": "1339022435",
    "goodreadsUrl": "https://www.goodreads.com/book/show/210708924-night-of-the-dream-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-29",
    "title": "Magic of the Wizard Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 29,
    "author": "Tracey West",
    "dateRead": "2026-07-10",
    "displayDateRead": "July 2026",
    "goodreadsRating": 4.35,
    "synopsis": "Zoltan has transformed himself into a Wizard Dragon, and he's planning to free the evil wizard Maldred! Drake and Worm team up with Zoltan's own son, Wolfgang, who wants to stop his father. Their journey takes them to Barga, where an Earth Dragon named Kinguq and her Dragon Master, Nanu, guard a secret door to the place where Maldred is trapped.",
    "coverFile": "covers/dragon-masters-29.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/133902246X",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/133902246X",
    "amazonCaExact": true,
    "coverIsbn": "133902246X",
    "goodreadsUrl": "https://www.goodreads.com/book/show/216879653-magic-of-the-wizard-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-30",
    "title": "Vortex of the Chaos Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 30,
    "author": "Tracey West",
    "dateRead": "2026-07-10",
    "displayDateRead": "July 2026",
    "goodreadsRating": 4.46,
    "synopsis": "The evil wizard Maldred has split into one hundred mini-Maldreds, and Dragon Masters everywhere are battling the chaos! Drake, Rori, Bo, and Ana travel to Goryeo to find Seong-Min the Chaos Dragon and her Dragon Master, Ji-Min — the only dragon powerful enough to stop Maldred for good. But even Ji-Min warns that the Chaos Dragon is incredibly hard to control.",
    "coverFile": "covers/dragon-masters-30.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1339022494",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1339022494",
    "amazonCaExact": true,
    "coverIsbn": "1339022494",
    "goodreadsUrl": "https://www.goodreads.com/book/show/221737156-vortex-of-the-chaos-dragon",
    "pages": 96
  },
  {
    "id": "dragon-masters-31",
    "title": "Defending the Swamp Dragon",
    "series": "Dragon Masters",
    "seriesNumber": 31,
    "author": "Tracey West",
    "dateRead": "2026-07-18",
    "displayDateRead": "July 18, 2026",
    "goodreadsRating": 4.39,
    "synopsis": "When the Dragon Stone reveals a new Dragon Master in a faraway mangrove swamp, Drake and Obi set off to find her. They meet Kinti, the new Dragon Master, but discover that the villagers have captured a Swamp Dragon they believe attacked her. Kinti knows the truth — the dragon was trying to warn her about a magical monster hiding in the swamp — so the friends must free the dragon and save the village.",
    "coverFile": "covers/dragon-masters-31.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/B0FK165TB8",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/B0FK165TB8",
    "amazonCaExact": true,
    "coverIsbn": null,
    "goodreadsUrl": "https://www.goodreads.com/book/show/239320094-defending-the-swamp-dragon",
    "pages": 96
  },
  {
    "id": "llama-quest-01",
    "title": "Danger in the Dragons' Den",
    "series": "Llama Quest",
    "seriesNumber": 1,
    "author": "Megan Reyes",
    "dateRead": "2026-06-15",
    "displayDateRead": "June 2026",
    "goodreadsRating": 4.04,
    "synopsis": "Eight-year-old Dak is swept into the magical kingdom of Ravenwood by Lucy, a talking purple llama. The kingdom's protective magic stones have gone missing, and without them Ravenwood and its creatures are in big trouble. With his new friend Fenn, Dak braves a den full of dragons to track down the missing Fire Stone and start putting things right.",
    "coverFile": "covers/llama-quest-01.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/0593808541",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/0593808541",
    "amazonCaExact": true,
    "coverIsbn": "0593808541",
    "goodreadsUrl": "https://www.goodreads.com/book/show/213197200-danger-in-the-dragons-den",
    "pages": 128
  },
  {
    "id": "llama-quest-02",
    "title": "Secrets of Starfall Forest",
    "series": "Llama Quest",
    "seriesNumber": 2,
    "author": "Megan Reyes",
    "dateRead": "2026-06-15",
    "displayDateRead": "June 2026",
    "goodreadsRating": 4.19,
    "synopsis": "Dak, Fenn, and Lucy the llama have found the Fire Stone, but eleven magical stones are still missing. Their next search takes them to Starfall Forest, home of the alicorns, winged horses with magical horns. The alicorns have the Star Stone, but it is leaking magic everywhere and turning a royal wedding upside down, so the team must find a way to fix things fast.",
    "coverFile": "covers/llama-quest-02.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/0593808576",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/0593808576",
    "amazonCaExact": true,
    "coverIsbn": "0593808576",
    "goodreadsUrl": "https://www.goodreads.com/book/show/213197156-llama-quest-2",
    "pages": 128
  },
  {
    "id": "llama-quest-03",
    "title": "Curse of the Quakes",
    "series": "Llama Quest",
    "seriesNumber": 3,
    "author": "Megan Reyes",
    "dateRead": "2026-07-10",
    "displayDateRead": "July 2026",
    "goodreadsRating": null,
    "synopsis": "When Lucy senses the missing Earth Stone, the team is whisked away to a farmers' festival in Silverglade Meadow, just as the ground starts to shake. The villagers blame the kitsune, magical three-tailed foxes from the nearby forest, but Dak and Fenn are not so sure. They must find the Earth Stone, outsmart a sneaky thief, and clear the foxes' names before the earthquakes wreck the festival.",
    "coverFile": "covers/llama-quest-03.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/0593808606",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/0593808606",
    "amazonCaExact": true,
    "coverIsbn": "0593808606",
    "goodreadsUrl": "https://www.goodreads.com/book/show/219334714-llama-quest-3",
    "pages": 128
  },
  {
    "id": "llama-quest-04",
    "title": "Search for the Sea Monster",
    "series": "Llama Quest",
    "seriesNumber": 4,
    "author": "Megan Reyes",
    "dateRead": "2026-07-10",
    "displayDateRead": "July 2026",
    "goodreadsRating": null,
    "synopsis": "Fresh from finding the Earth Stone, Dak, Fenn, and Lucy learn that the Water Stone is hidden deep under the sea. With help from some friendly merkids, they dive into an underwater world where an angry kraken is causing chaos. It turns out the giant creature is searching for her lost son, and the team must find both the stone and the missing kraken before a thief beats them to it.",
    "coverFile": "covers/llama-quest-04.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/0593808630",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/0593808630",
    "amazonCaExact": true,
    "coverIsbn": "0593808630",
    "goodreadsUrl": null,
    "pages": 128
  },
  {
    "id": "kwames-magic-quest-01",
    "title": "Rise of the Green Flame",
    "series": "Kwame's Magic Quest",
    "seriesNumber": 1,
    "author": "Bernard Mensah",
    "dateRead": "2026-06-15",
    "displayDateRead": "June 2026",
    "goodreadsRating": 3.92,
    "synopsis": "Eight-year-old Kwame has just started at Nkonyaa School, where kids in Ghana learn to use magic — but no matter how hard he tries, his own powers won't wake up. Then his best friend Fifi starts acting very strangely, and Kwame suspects a dangerous magical object is to blame. He'll have to find the magic inside himself in time to save his friend.",
    "coverFile": "covers/kwames-magic-quest-01.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338843281",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338843281",
    "amazonCaExact": true,
    "coverIsbn": "1338843281",
    "goodreadsUrl": "https://www.goodreads.com/book/show/83821759-rise-of-the-green-flame",
    "pages": 96
  },
  {
    "id": "kwames-magic-quest-02",
    "title": "Race to the Magic Mountain",
    "series": "Kwame's Magic Quest",
    "seriesNumber": 2,
    "author": "Bernard Mensah",
    "dateRead": "2026-06-15",
    "displayDateRead": "June 2026",
    "goodreadsRating": 4.14,
    "synopsis": "An evil magic has turned Kwame's friend Fifi into a green flame and snatched the two most powerful calabashes in the land. Now Kwame and his friends Esi and Papa-Kow must race to the Magic Mountain before the green flame can fuse the calabashes into one unstoppable source of power. Can they stop it in time and bring Fifi back?",
    "coverFile": "covers/kwames-magic-quest-02.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338843311",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338843311",
    "amazonCaExact": true,
    "coverIsbn": "1338843311",
    "goodreadsUrl": "https://www.goodreads.com/book/show/195261537-race-to-the-magic-mountain",
    "pages": 96
  },
  {
    "id": "kwames-magic-quest-03",
    "title": "Bite of the Kaba Lagoon",
    "series": "Kwame's Magic Quest",
    "seriesNumber": 3,
    "author": "Bernard Mensah",
    "dateRead": "2026-06-15",
    "displayDateRead": "June 2026",
    "goodreadsRating": 4.27,
    "synopsis": "The magical Nkonyaa Tree is losing its power — and if it fades completely, everyone's magic will disappear with it. Even worse, Principal Wari and Kwame's friend Fifi are being blamed, and the Grand Elder wants to banish them to the Dark Void. Kwame and Esi brave the dangerous Kaba Lagoon to fetch a rare ingredient for a spell that could heal the tree and clear their friends' names.",
    "coverFile": "covers/kwames-magic-quest-03.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338843346",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338843346",
    "amazonCaExact": true,
    "coverIsbn": "1338843346",
    "goodreadsUrl": null,
    "pages": 96
  },
  {
    "id": "kwames-magic-quest-04",
    "title": "Curse of the Akoma Stone",
    "series": "Kwame's Magic Quest",
    "seriesNumber": 4,
    "author": "Bernard Mensah",
    "dateRead": "2026-07-10",
    "displayDateRead": "July 2026",
    "goodreadsRating": 4.6,
    "synopsis": "Kwame and his friends can't wait to compete in the Nkonyaa Games, a series of exciting magic contests. But when a mysterious new teacher called Elder Z shows up, two students are suddenly trapped in stone by a curse. The tricky Boni calabash tells Kwame the only way to free his classmates is to enter the Cursed Realm himself.",
    "coverFile": "covers/kwames-magic-quest-04.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338843370",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338843370",
    "amazonCaExact": true,
    "coverIsbn": "1338843370",
    "goodreadsUrl": "https://www.goodreads.com/book/show/216879621-curse-of-the-akoma-stone",
    "pages": 96
  },
  {
    "id": "pets-rule-01",
    "title": "My Kingdom of Darkness",
    "series": "Pets Rule!",
    "seriesNumber": 1,
    "author": "Susan Tan",
    "dateRead": "2026-07-17",
    "displayDateRead": "July 17, 2026",
    "goodreadsRating": 4.16,
    "synopsis": "Ember the chihuahua may be small and adorable, but he is absolutely certain he's an evil overlord destined to rule the world. Newly adopted into a family, he sets out to conquer his kingdom — starting with the house and backyard. But first this pint-sized emperor of darkness must deal with his sworn enemies: the scheming squirrels.",
    "coverFile": "covers/pets-rule-01.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338756338",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338756338",
    "amazonCaExact": true,
    "coverIsbn": "1338756338",
    "goodreadsUrl": "https://www.goodreads.com/book/show/58719187-my-kingdom-of-darkness",
    "pages": 96
  },
  {
    "id": "last-firehawk-01",
    "title": "The Ember Stone",
    "series": "The Last Firehawk",
    "seriesNumber": 1,
    "author": "Katrina Charman",
    "dateRead": "2026-04-15",
    "displayDateRead": "April 2026",
    "goodreadsRating": 4.27,
    "synopsis": "Tag is a small owl who dreams of joining the Owls of Valor, the guards who protect the land of Perodia. When he and his squirrel friend Skyla discover a mysterious egg, out hatches Blaze, the very last firehawk. Together the three friends set off to find the pieces of the magical Ember Stone, the only thing powerful enough to stop the evil vulture Thorn and the dark Shadow he is spreading across the land.",
    "coverFile": "covers/last-firehawk-01.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338122134",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338122134",
    "amazonCaExact": true,
    "coverIsbn": "1338122134",
    "goodreadsUrl": "https://www.goodreads.com/book/show/34334480-the-ember-stone",
    "pages": 96
  },
  {
    "id": "last-firehawk-02",
    "title": "The Crystal Caverns",
    "series": "The Last Firehawk",
    "seriesNumber": 2,
    "author": "Katrina Charman",
    "dateRead": "2026-04-15",
    "displayDateRead": "April 2026",
    "goodreadsRating": 4.42,
    "synopsis": "Tag, Skyla, and Blaze head north over the Jagged Mountains to the icy Crystal Caverns, where the next piece of the Ember Stone is hidden. Along the way they battle a wild snowstorm, rescue a lost seal, and dodge Thorn's sneaky ice-leopard spies. Blaze's firehawk powers are growing, but she is still learning to control them, and the friends end up trapped in an ice cave.",
    "coverFile": "covers/last-firehawk-02.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338122517",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338122517",
    "amazonCaExact": true,
    "coverIsbn": "1338122517",
    "goodreadsUrl": "https://www.goodreads.com/book/show/34645544",
    "pages": 96
  },
  {
    "id": "last-firehawk-03",
    "title": "The Whispering Oak",
    "series": "The Last Firehawk",
    "seriesNumber": 3,
    "author": "Katrina Charman",
    "dateRead": "2026-05-15",
    "displayDateRead": "May 2026",
    "goodreadsRating": 4.45,
    "synopsis": "The magical map leads Tag, Skyla, and Blaze to the giant Whispering Oak, where another piece of the Ember Stone is hidden. There they meet buzzing little creatures called grumblebees and discover new dangers waiting in the branches. With Thorn's spies close behind, the friends must work together to keep the stone out of the vulture's claws.",
    "coverFile": "covers/last-firehawk-03.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/133812255X",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/133812255X",
    "amazonCaExact": true,
    "coverIsbn": "133812255X",
    "goodreadsUrl": "https://www.goodreads.com/book/show/35849474-the-whispering-oak",
    "pages": 96
  },
  {
    "id": "last-firehawk-04",
    "title": "Lullaby Lake",
    "series": "The Last Firehawk",
    "seriesNumber": 4,
    "author": "Katrina Charman",
    "dateRead": "2026-05-15",
    "displayDateRead": "May 2026",
    "goodreadsRating": 4.49,
    "synopsis": "The hunt for the Ember Stone brings Tag, Skyla, and Blaze to Lullaby Lake, but disaster strikes when their piece of the stone sinks into the water. Every time they try to dive for it, the lake's strange magic sings them to sleep. The friends discover that water sprites called nixies guard the lake, and they must earn their trust before Thorn catches up.",
    "coverFile": "covers/last-firehawk-04.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338122673",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338122673",
    "amazonCaExact": true,
    "coverIsbn": "1338122673",
    "goodreadsUrl": "https://www.goodreads.com/book/show/36127400-lullaby-lake",
    "pages": 96
  },
  {
    "id": "last-firehawk-05",
    "title": "The Shadowlands",
    "series": "The Last Firehawk",
    "seriesNumber": 5,
    "author": "Katrina Charman",
    "dateRead": "2026-06-15",
    "displayDateRead": "June 2026",
    "goodreadsRating": 4.51,
    "synopsis": "The Ember Stone is almost complete, and only one piece is left to find. To get it, Tag, Skyla, and Blaze must cross the Shadowlands, the darkest and most dangerous part of Perodia and the home of Thorn himself. The closer they get, the stronger the Shadow grows, and the friends will need all their courage to make it through.",
    "coverFile": "covers/last-firehawk-05.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338307118",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338307118",
    "amazonCaExact": true,
    "coverIsbn": "1338307118",
    "goodreadsUrl": "https://www.goodreads.com/book/show/39983527-the-shadowlands",
    "pages": 96
  },
  {
    "id": "last-firehawk-06",
    "title": "The Battle for Perodia",
    "series": "The Last Firehawk",
    "seriesNumber": 6,
    "author": "Katrina Charman",
    "dateRead": "2026-06-15",
    "displayDateRead": "June 2026",
    "goodreadsRating": 4.56,
    "synopsis": "The time has come for the final showdown to save Perodia. Tag, Skyla, and Blaze gather all their friends for a great battle against Thorn and his army of spies. Blaze must finally learn to unleash the full magic of the Ember Stone, and everyone hopes it will be strong enough to drive the Shadow away for good.",
    "coverFile": "covers/last-firehawk-06.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338307142",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338307142",
    "amazonCaExact": true,
    "coverIsbn": "1338307142",
    "goodreadsUrl": "https://www.goodreads.com/book/show/41473875-the-battle-for-perodia",
    "pages": 96
  },
  {
    "id": "last-firehawk-07",
    "title": "The Cloud Kingdom",
    "series": "The Last Firehawk",
    "seriesNumber": 7,
    "author": "Katrina Charman",
    "dateRead": "2026-07-10",
    "displayDateRead": "July 2026",
    "goodreadsRating": 4.47,
    "synopsis": "With Perodia safe, Blaze sets out on a brand-new quest: finding her long-lost firehawk family. The only clues Tag, Skyla, and Blaze have are three golden feathers, which point them toward a hidden portal to the magical Cloud Kingdom. Getting there is only the beginning, because the kingdom in the sky is full of surprises.",
    "coverFile": "covers/last-firehawk-07.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338307177",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338307177",
    "amazonCaExact": true,
    "coverIsbn": "1338307177",
    "goodreadsUrl": "https://www.goodreads.com/book/show/43319695-the-cloud-kingdom",
    "pages": 96
  },
  {
    "id": "last-firehawk-08",
    "title": "The Silver Swamp",
    "series": "The Last Firehawk",
    "seriesNumber": 8,
    "author": "Katrina Charman",
    "dateRead": "2026-07-10",
    "displayDateRead": "July 2026",
    "goodreadsRating": 4.49,
    "synopsis": "Blaze has been snatched by giant birds, and Tag and Skyla must journey through the Cloud Kingdom to rescue her with only their magical map to guide them. Their path leads through the spooky Silver Swamp, where danger hides around every bend and Skyla is struck by a poisonous glitter. The friends must also decide whether to trust a mysterious stranger named Claw, who says he is Thorn's twin brother.",
    "coverFile": "covers/last-firehawk-08.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338565311",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338565311",
    "amazonCaExact": true,
    "coverIsbn": "1338565311",
    "goodreadsUrl": "https://www.goodreads.com/book/show/50161148-the-silver-swamp",
    "pages": 96
  },
  {
    "id": "pixie-tricks-01",
    "title": "Sprite's Secret",
    "series": "Pixie Tricks",
    "seriesNumber": 1,
    "author": "Tracey West",
    "dateRead": "2026-07-18",
    "displayDateRead": "July 18, 2026",
    "goodreadsRating": 4.07,
    "synopsis": "When fourteen fairies escape from the magical Otherworld, a tiny pixie named Sprite is sent to trick them all back home — and he recruits a girl named Violet to help. Their first target is Pix, a mischievous fairy who makes everyone want to play games all day long and never stop. Violet and Sprite will need some clever tricks of their own to send him back where he belongs.",
    "coverFile": "covers/pixie-tricks-01.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338627783",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338627783",
    "amazonCaExact": true,
    "coverIsbn": "1338627783",
    "goodreadsUrl": "https://www.goodreads.com/book/show/923930.Sprite_s_Secret",
    "pages": 96
  },
  {
    "id": "pixie-tricks-03",
    "title": "The Pet Store Sprite",
    "series": "Pixie Tricks",
    "seriesNumber": 3,
    "author": "Tracey West",
    "dateRead": "2026-07-18",
    "displayDateRead": "July 18, 2026",
    "goodreadsRating": 3.96,
    "synopsis": "Faucets are dripping and pipes are bursting all over town, and the culprit is Aquamarina — a runaway water sprite who has made herself at home in the pet store fish tank. Violet teams up with her cousin Leon and her pixie friend Sprite to outsmart her, but there's something extra fishy about Aquamarina's games. Can they trick her back to the Otherworld without ending up in the deep end? (Note: the 2020s Scholastic Branches reissue publishes this Aquamarina adventure as 'The Pet Store Sprite', Pixie Tricks #3 — no edition is titled 'Aquamarina's Folly'.)",
    "coverFile": "covers/pixie-tricks-03.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1338627848",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1338627848",
    "amazonCaExact": true,
    "coverIsbn": "1338627848",
    "goodreadsUrl": "https://www.goodreads.com/book/show/18649267-the-pet-store-sprite",
    "pages": 96
  },
  {
    "id": "coral-keepers-01",
    "title": "Search for the Silver Shell",
    "series": "Coral Keepers",
    "seriesNumber": 1,
    "author": "Robin Yardi",
    "dateRead": "2026-07-18",
    "displayDateRead": "July 18, 2026",
    "goodreadsRating": null,
    "synopsis": "Mermaid princess Finn dreams of becoming a Coral Keeper — one of the magicians sworn to protect the underwater Queendom of Anjeea. There's just one problem: she keeps struggling with her shark-magic test. When the evil magician Rozaro plots to steal the throne, Finn and her friends Moon and Link must track down the legendary Silver Shell, the only power strong enough to stop him.",
    "coverFile": "covers/coral-keepers-01.jpg",
    "amazonUsUrl": "https://www.amazon.com/dp/1546122427",
    "amazonUsExact": true,
    "amazonCaUrl": "https://www.amazon.ca/dp/1546122427",
    "amazonCaExact": true,
    "coverIsbn": "1546122427",
    "goodreadsUrl": "https://www.goodreads.com/book/show/213083755-search-for-the-silver-shell",
    "pages": 96
  }
];
